<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: /mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/System/Manager/NRE_SystemManager.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_b1a122bf62c958266ec5bf64d14fde5a.php">ECS</a></li><li class="navelem"><a class="el" href="dir_3a0ad7289f82990986345da35b146158.php">System</a></li><li class="navelem"><a class="el" href="dir_d2b3eb3b820ea89e416019dba41ec760.php">Manager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_SystemManager.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___system_manager_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;cassert&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;bitset&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &lt;memory&gt;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">    #include &lt;Header/NRE_Utility.hpp&gt;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="preprocessor">    #include &quot;../NRE_System.hpp&quot;</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_e_c_s.php">ECS</a> {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;</div><div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php">   36</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php">SystemManager</a> : <span class="keyword">public</span> Utility::Singleton&lt;SystemManager&gt; {</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                <span class="keyword">friend</span> Utility::Singleton&lt;SystemManager&gt;;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                    constexpr <span class="keyword">static</span> <span class="keywordtype">int</span> MAX_SYSTEM = 32;                       </div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                    <span class="keywordtype">bool</span> initialized;                                           </div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    Utility::Vector&lt;std::unique_ptr&lt;AbstractSystem&gt;&gt; systems;   </div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    std::bitset&lt;MAX_SYSTEM&gt; mask;                               </div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;<span class="comment"></span>                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;                        T* <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a06ba6ff5e300b22f6e392cfb0e75319f">getSystem</a>();</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;<span class="comment"></span>                        <span class="keyword">template</span> &lt;<span class="keyword">class </span>T, <span class="keyword">class </span>... Args&gt;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a5df28f5f679e047dfe0a542192896353">add</a>(Args &amp;&amp; ... args);</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                        <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a01017c20cc72cd42f54207f0074c4601">update</a>();</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#af310e9ee3b6e45e4d03dd811392c2546">updateAll</a>();</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a74e8059b19200ac24edd8fe73c2e65b5">configure</a>();</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;                <span class="keyword">private</span>:   <span class="comment">// Methods</span></div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php">SystemManager</a>();</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                <span class="keyword">public</span>:     <span class="comment">// Static</span></div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;<span class="comment"></span>                    <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;                    <span class="keyword">static</span> T* <span class="keyword">get</span>();</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;            };</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;        }</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;    }</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;<span class="preprocessor">    #include &quot;NRE_SystemManager.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_system_manager_php_a5df28f5f679e047dfe0a542192896353"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a5df28f5f679e047dfe0a542192896353">NRE::ECS::SystemManager::add</a></div><div class="ttdeci">void add(Args &amp;&amp;...args)</div></div>
<div class="ttc" id="namespace_e_c_s_php"><div class="ttname"><a href="namespace_e_c_s.php">ECS</a></div><div class="ttdoc">ECS&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_system_manager_php_a06ba6ff5e300b22f6e392cfb0e75319f"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a06ba6ff5e300b22f6e392cfb0e75319f">NRE::ECS::SystemManager::getSystem</a></div><div class="ttdeci">T * getSystem()</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_system_manager_php_a74e8059b19200ac24edd8fe73c2e65b5"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a74e8059b19200ac24edd8fe73c2e65b5">NRE::ECS::SystemManager::configure</a></div><div class="ttdeci">void configure()</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_system_manager_php_af310e9ee3b6e45e4d03dd811392c2546"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#af310e9ee3b6e45e4d03dd811392c2546">NRE::ECS::SystemManager::updateAll</a></div><div class="ttdeci">void updateAll()</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_system_manager_php_a01017c20cc72cd42f54207f0074c4601"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a01017c20cc72cd42f54207f0074c4601">NRE::ECS::SystemManager::update</a></div><div class="ttdeci">void update()</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_system_manager_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php">NRE::ECS::SystemManager</a></div><div class="ttdoc">Manage system storing and update. </div><div class="ttdef"><b>Definition:</b> NRE_SystemManager.hpp:36</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
