<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: /mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/System/NRE_System.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_b1a122bf62c958266ec5bf64d14fde5a.php">ECS</a></li><li class="navelem"><a class="el" href="dir_3a0ad7289f82990986345da35b146158.php">System</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_System.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___system_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;string&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___abstract_system_8hpp.php">NRE_AbstractSystem.hpp</a>&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_e_c_s.php">ECS</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_system.php">   33</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system.php">System</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a> {</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system.php#a2b894f5b259792fa6c0f743ebd05ee5e">~System</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                <span class="keyword">public</span>:     <span class="comment">// Static</span></div><div class="line"><a name="l00046"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_system.php#a8e9d9a9a6ddafa1594bba2a5d860eee2">   46</a></span>&#160;<span class="comment"></span>                    <span class="keyword">static</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">Category</a> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_system.php#a8e9d9a9a6ddafa1594bba2a5d860eee2">getCategory</a>() {</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                        <span class="keyword">static</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">Category</a> category = <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a9f5f3b58fb52edb02a639063b189ecd2">counter</a>++;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                        <span class="keywordflow">return</span> category;</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                    }</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;            };</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;        }</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;    }</div><div class="ttc" id="namespace_e_c_s_php"><div class="ttname"><a href="namespace_e_c_s.php">ECS</a></div><div class="ttdoc">ECS&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_abstract_system_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">NRE::ECS::AbstractSystem</a></div><div class="ttdoc">Base class for template system. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractSystem.hpp:31</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_system_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_system.php">NRE::ECS::System</a></div><div class="ttdoc">Base class for user defined system. </div><div class="ttdef"><b>Definition:</b> NRE_System.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_system_php_a8e9d9a9a6ddafa1594bba2a5d860eee2"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_system.php#a8e9d9a9a6ddafa1594bba2a5d860eee2">NRE::ECS::System::getCategory</a></div><div class="ttdeci">static Category getCategory()</div><div class="ttdef"><b>Definition:</b> NRE_System.hpp:46</div></div>
<div class="ttc" id="_n_r_e___abstract_system_8hpp_php"><div class="ttname"><a href="_n_r_e___abstract_system_8hpp.php">NRE_AbstractSystem.hpp</a></div><div class="ttdoc">Implementation of ECS&amp;#39;s API Object : AbstractSystem. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_abstract_system_php_a9f5f3b58fb52edb02a639063b189ecd2"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a9f5f3b58fb52edb02a639063b189ecd2">NRE::ECS::AbstractSystem::counter</a></div><div class="ttdeci">static Category counter</div><div class="ttdef"><b>Definition:</b> NRE_AbstractSystem.hpp:75</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_system_php_a2b894f5b259792fa6c0f743ebd05ee5e"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_system.php#a2b894f5b259792fa6c0f743ebd05ee5e">NRE::ECS::System::~System</a></div><div class="ttdeci">virtual ~System()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_abstract_system_php_a41c3f5fea8c82d7f523a040d0d37bfaa"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">NRE::ECS::AbstractSystem::Category</a></div><div class="ttdeci">std::size_t Category</div><div class="ttdef"><b>Definition:</b> NRE_AbstractSystem.hpp:34</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
