<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: /mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Id/NRE_Id.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_b1a122bf62c958266ec5bf64d14fde5a.php">ECS</a></li><li class="navelem"><a class="el" href="dir_b3425cf3684a72a972685eae55fae74b.php">Entity</a></li><li class="navelem"><a class="el" href="dir_195607172ac1a925227ad8dc33934fdc.php">Id</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Id.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___id_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;string&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;cstdint&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00022"></a><span class="lineno"><a class="line" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">   22</a></span>&#160;        <span class="keyword">typedef</span> std::uint32_t <a class="code" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>;</div><div class="line"><a name="l00024"></a><span class="lineno"><a class="line" href="namespace_n_r_e.php#aaabd8e7d9cfeba48def9efc5cb73ef27">   24</a></span>&#160;        <span class="keyword">typedef</span> std::uint64_t <a class="code" href="namespace_n_r_e.php#aaabd8e7d9cfeba48def9efc5cb73ef27">uint64</a>;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_e_c_s.php">ECS</a> {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;</div><div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_id.php">   36</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> {</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                    uint64 id;  </div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#aa5d2c551c93988f227d2aa35c4c62f08">Id</a>();</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#aa5d2c551c93988f227d2aa35c4c62f08">Id</a>(uint64 i);</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#aa5d2c551c93988f227d2aa35c4c62f08">Id</a>(uint32 index, uint32 version);</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#aa5d2c551c93988f227d2aa35c4c62f08">Id</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> <span class="keyword">const</span>&amp; i) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                    <span class="comment">//## Move-Constructor ##//</span></div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#aa5d2c551c93988f227d2aa35c4c62f08">Id</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> &amp;&amp; i) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a6ade0f17fd29b06cd5be97af1bbeac03">~Id</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;<span class="comment"></span>                        uint64 <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a7abbef77570120cd668c8ea7a53a32ec">getId</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;                        uint32 <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a63b1c5ebf58c54c87576e36625bca56c">getIndex</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;                        uint32 <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#af65965c2545bdd0803e4e3141cc8abf5">getVersion</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&amp; <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a312e9a61948a3895d50c278d76457198">operator =</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> <span class="keyword">const</span>&amp; i) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&amp; <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a312e9a61948a3895d50c278d76457198">operator =</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> &amp;&amp; i) = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;                    <span class="comment">//## Comparison Operator ##//</span></div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a57d75c8896bc246cc582488324549e73">operator ==</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> <span class="keyword">const</span>&amp; i) <span class="keyword">const</span>;</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a87bdc21282adae93e7e9a57acfb09f17">operator !=</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> <span class="keyword">const</span>&amp; i) <span class="keyword">const</span>;</div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a488ce8e54da3d06b98ea5d1204e79871">operator &lt;</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> <span class="keyword">const</span>&amp; i) <span class="keyword">const</span>;</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;            };</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;        }</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;    }</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;</div><div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;<span class="preprocessor">    #include &quot;NRE_Id.tpp&quot;</span></div><div class="ttc" id="namespace_e_c_s_php"><div class="ttname"><a href="namespace_e_c_s.php">ECS</a></div><div class="ttdoc">ECS&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php_a488ce8e54da3d06b98ea5d1204e79871"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php#a488ce8e54da3d06b98ea5d1204e79871">NRE::ECS::Id::operator&lt;</a></div><div class="ttdeci">bool operator&lt;(Id const &amp;i) const </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php_a312e9a61948a3895d50c278d76457198"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php#a312e9a61948a3895d50c278d76457198">NRE::ECS::Id::operator=</a></div><div class="ttdeci">Id &amp; operator=(Id const &amp;i)=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php_a6ade0f17fd29b06cd5be97af1bbeac03"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php#a6ade0f17fd29b06cd5be97af1bbeac03">NRE::ECS::Id::~Id</a></div><div class="ttdeci">~Id()=default</div></div>
<div class="ttc" id="namespace_n_r_e_php_aaabd8e7d9cfeba48def9efc5cb73ef27"><div class="ttname"><a href="namespace_n_r_e.php#aaabd8e7d9cfeba48def9efc5cb73ef27">NRE::uint64</a></div><div class="ttdeci">std::uint64_t uint64</div><div class="ttdef"><b>Definition:</b> NRE_Id.hpp:24</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php_aa5d2c551c93988f227d2aa35c4c62f08"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php#aa5d2c551c93988f227d2aa35c4c62f08">NRE::ECS::Id::Id</a></div><div class="ttdeci">Id()</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php_a57d75c8896bc246cc582488324549e73"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php#a57d75c8896bc246cc582488324549e73">NRE::ECS::Id::operator==</a></div><div class="ttdeci">bool operator==(Id const &amp;i) const </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php_a87bdc21282adae93e7e9a57acfb09f17"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php#a87bdc21282adae93e7e9a57acfb09f17">NRE::ECS::Id::operator!=</a></div><div class="ttdeci">bool operator!=(Id const &amp;i) const </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php_a63b1c5ebf58c54c87576e36625bca56c"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php#a63b1c5ebf58c54c87576e36625bca56c">NRE::ECS::Id::getIndex</a></div><div class="ttdeci">uint32 getIndex() const </div></div>
<div class="ttc" id="namespace_n_r_e_php_aa87ccdbfdf4cc8a17853dbcbd09cfa18"><div class="ttname"><a href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">NRE::uint32</a></div><div class="ttdeci">std::uint32_t uint32</div><div class="ttdef"><b>Definition:</b> NRE_Id.hpp:22</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php">NRE::ECS::Id</a></div><div class="ttdoc">An entity Id. </div><div class="ttdef"><b>Definition:</b> NRE_Id.hpp:36</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php_af65965c2545bdd0803e4e3141cc8abf5"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php#af65965c2545bdd0803e4e3141cc8abf5">NRE::ECS::Id::getVersion</a></div><div class="ttdeci">uint32 getVersion() const </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_id_php_a7abbef77570120cd668c8ea7a53a32ec"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_id.php#a7abbef77570120cd668c8ea7a53a32ec">NRE::ECS::Id::getId</a></div><div class="ttdeci">uint64 getId() const </div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
