<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: /mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/Iterator/NRE_ViewIterator.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_b1a122bf62c958266ec5bf64d14fde5a.php">ECS</a></li><li class="navelem"><a class="el" href="dir_b3425cf3684a72a972685eae55fae74b.php">Entity</a></li><li class="navelem"><a class="el" href="dir_506b361a64b5c3fb8c72eb8d6abb6c67.php">Manager</a></li><li class="navelem"><a class="el" href="dir_73723887d630f5da8d29f5a815db9909.php">Iterator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_ViewIterator.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___view_iterator_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;string&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="preprocessor">    #include &lt;iterator&gt;</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &lt;algorithm&gt;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">    #include &quot;../NRE_EntityManager.hpp&quot;</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="preprocessor">    #include &quot;../../Id/NRE_Id.hpp&quot;</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_e_c_s.php">ECS</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T, <span class="keywordtype">bool</span> All = false&gt;</div><div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">   36</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">ViewIterator</a> : <span class="keyword">public</span> std::iterator&lt;std::input_iterator_tag, Id&gt; {</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                    <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> mask;  </div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                    <a class="code" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> index;                       </div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;                    std::size_t capacity;               </div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    std::size_t freeCursor;             </div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9701e377e9c70c6d842ce09c08280c78">ViewIterator</a>() = <span class="keyword">delete</span>;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9701e377e9c70c6d842ce09c08280c78">ViewIterator</a>(<a class="code" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> i);</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9701e377e9c70c6d842ce09c08280c78">ViewIterator</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> <span class="keyword">const</span> m, <a class="code" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> i);</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9073e325fd31867c1e849521de1298bc">~ViewIterator</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a6a59facd435e716218c86772453f5a08">next</a>();</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a272be19d31f3f6ea28e8e8a7916ee6ff">predicate</a>();</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#ab21d102dfe4f120918069a9ff0f17b86">validEntity</a>();</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;                    <span class="comment">//## Access Operator ##//</span></div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a8bb27527b0b79690886f9ac1f723bb66">operator *</a>();</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;                        <span class="keyword">const</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a8bb27527b0b79690886f9ac1f723bb66">operator *</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;                    <span class="comment">//## Arithmetic Operator ##//</span></div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;<span class="comment"></span>                        T&amp; <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a602c15071a7c8e439917b1748d32c861">operator++</a>();</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                    <span class="comment">//## Comparison Operator ##//</span></div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;<span class="comment"></span>                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a1831ae17abb095e7d65c71f254a6a83e">operator==</a>(T <span class="keyword">const</span>&amp; rhs) <span class="keyword">const</span>;</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;                        <span class="keywordtype">bool</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a2e5b536dc3b520fa335bdeac5de9a29e">operator!=</a>(T <span class="keyword">const</span>&amp; rhs) <span class="keyword">const</span>;</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;            };</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;        }</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;    }</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;<span class="preprocessor">    #include &quot;NRE_ViewIterator.tpp&quot;</span></div><div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_a9701e377e9c70c6d842ce09c08280c78"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9701e377e9c70c6d842ce09c08280c78">NRE::ECS::ViewIterator::ViewIterator</a></div><div class="ttdeci">ViewIterator()=delete</div></div>
<div class="ttc" id="namespace_e_c_s_php"><div class="ttname"><a href="namespace_e_c_s.php">ECS</a></div><div class="ttdoc">ECS&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_ab21d102dfe4f120918069a9ff0f17b86"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#ab21d102dfe4f120918069a9ff0f17b86">NRE::ECS::ViewIterator::validEntity</a></div><div class="ttdeci">bool validEntity()</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a></div><div class="ttdoc">An iterator over a view of entities. </div><div class="ttdef"><b>Definition:</b> NRE_ViewIterator.hpp:36</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_a2e5b536dc3b520fa335bdeac5de9a29e"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a2e5b536dc3b520fa335bdeac5de9a29e">NRE::ECS::ViewIterator::operator!=</a></div><div class="ttdeci">bool operator!=(T const &amp;rhs) const </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_entity_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_entity.php">NRE::ECS::Entity</a></div><div class="ttdoc">A basic entity. </div><div class="ttdef"><b>Definition:</b> NRE_Entity.hpp:43</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_a272be19d31f3f6ea28e8e8a7916ee6ff"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a272be19d31f3f6ea28e8e8a7916ee6ff">NRE::ECS::ViewIterator::predicate</a></div><div class="ttdeci">bool predicate()</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_a1831ae17abb095e7d65c71f254a6a83e"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a1831ae17abb095e7d65c71f254a6a83e">NRE::ECS::ViewIterator::operator==</a></div><div class="ttdeci">bool operator==(T const &amp;rhs) const </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_entity_manager_php_af55ac31ee3c7cb0bcd8e26ccb26b5868"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">NRE::ECS::EntityManager::ComponentMask</a></div><div class="ttdeci">std::bitset&lt; AbstractComponent::MAX_COMPONENTS &gt; ComponentMask</div><div class="ttdef"><b>Definition:</b> NRE_EntityManager.hpp:52</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_a9073e325fd31867c1e849521de1298bc"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9073e325fd31867c1e849521de1298bc">NRE::ECS::ViewIterator::~ViewIterator</a></div><div class="ttdeci">virtual ~ViewIterator()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_a602c15071a7c8e439917b1748d32c861"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a602c15071a7c8e439917b1748d32c861">NRE::ECS::ViewIterator::operator++</a></div><div class="ttdeci">T &amp; operator++()</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_a6a59facd435e716218c86772453f5a08"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a6a59facd435e716218c86772453f5a08">NRE::ECS::ViewIterator::next</a></div><div class="ttdeci">void next()</div></div>
<div class="ttc" id="namespace_n_r_e_php_aa87ccdbfdf4cc8a17853dbcbd09cfa18"><div class="ttname"><a href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">NRE::uint32</a></div><div class="ttdeci">std::uint32_t uint32</div><div class="ttdef"><b>Definition:</b> NRE_Id.hpp:22</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_a8bb27527b0b79690886f9ac1f723bb66"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a8bb27527b0b79690886f9ac1f723bb66">NRE::ECS::ViewIterator::operator*</a></div><div class="ttdeci">Entity operator*()</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
