<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: /mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/Iterator/View/NRE_View.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_b1a122bf62c958266ec5bf64d14fde5a.php">ECS</a></li><li class="navelem"><a class="el" href="dir_b3425cf3684a72a972685eae55fae74b.php">Entity</a></li><li class="navelem"><a class="el" href="dir_506b361a64b5c3fb8c72eb8d6abb6c67.php">Manager</a></li><li class="navelem"><a class="el" href="dir_73723887d630f5da8d29f5a815db9909.php">Iterator</a></li><li class="navelem"><a class="el" href="dir_2538ef0c7acee28898444f7d785a41f8.php">View</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_View.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___view_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;string&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &quot;../NRE_ViewIterator.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_e_c_s.php">ECS</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;            <span class="keyword">template</span> &lt;<span class="keywordtype">bool</span> All&gt;</div><div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_view.php">   33</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php">View</a> {</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                <span class="keyword">private</span>:    <span class="comment">//Fields</span></div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                    <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> mask;  </div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                <span class="keyword">public</span>:     <span class="comment">//Fields</span></div><div class="line"><a name="l00042"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">   42</a></span>&#160;<span class="comment"></span>                    <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">ViewIterator</a>&lt;Iterator, All&gt; {</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                    <span class="keyword">public</span>: <span class="comment">// Fields</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                        <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;<span class="comment"></span>                            <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php#a12818e8241e8e1f634ec2b739a6bfa58">Iterator</a>() = <span class="keyword">delete</span>;</div><div class="line"><a name="l00054"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php#a05a6e24deb9055cc81ef965bdc78a9c1">   54</a></span>&#160;                            <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php#a05a6e24deb9055cc81ef965bdc78a9c1">Iterator</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> <span class="keyword">const</span> m, <a class="code" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> i) : <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">ViewIterator</a>&lt;<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a>, All&gt;(m, i) {</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;                                <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a6a59facd435e716218c86772453f5a08">ViewIterator&lt;Iterator, All&gt;::next</a>();</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                            }</div><div class="line"><a name="l00060"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php#a937cc9b21e581593c213de18ae0067de">   60</a></span>&#160;                            <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php#a937cc9b21e581593c213de18ae0067de">nextEntity</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a>&amp;) {</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                            }</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                    };</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php#afd2527c49829479e17b435651eabd008">View</a>();</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php#afd2527c49829479e17b435651eabd008">View</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> m);</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php#abbd9b374abea285a601d449234cacb46">~View</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php#a8906736592a8a124b6bf6d781416a422">begin</a>();</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> <span class="keyword">const</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php#a8906736592a8a124b6bf6d781416a422">begin</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php#a0d91d3b3bbb90886dc8dd8ebbab33281">end</a>();</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> <span class="keyword">const</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php#a0d91d3b3bbb90886dc8dd8ebbab33281">end</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;            };</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;        }</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;    }</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;<span class="preprocessor">    #include &quot;NRE_View.tpp&quot;</span></div><div class="ttc" id="namespace_e_c_s_php"><div class="ttname"><a href="namespace_e_c_s.php">ECS</a></div><div class="ttdoc">ECS&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator_php_a12818e8241e8e1f634ec2b739a6bfa58"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php#a12818e8241e8e1f634ec2b739a6bfa58">NRE::ECS::View::Iterator::Iterator</a></div><div class="ttdeci">Iterator()=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view.php">NRE::ECS::View</a></div><div class="ttdoc">Base view for advanced iterator. </div><div class="ttdef"><b>Definition:</b> NRE_View.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a></div><div class="ttdoc">An iterator over a view of entities. </div><div class="ttdef"><b>Definition:</b> NRE_ViewIterator.hpp:36</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator_php_a937cc9b21e581593c213de18ae0067de"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php#a937cc9b21e581593c213de18ae0067de">NRE::ECS::View::Iterator::nextEntity</a></div><div class="ttdeci">void nextEntity(Entity &amp;)</div><div class="ttdef"><b>Definition:</b> NRE_View.hpp:60</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_entity_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_entity.php">NRE::ECS::Entity</a></div><div class="ttdoc">A basic entity. </div><div class="ttdef"><b>Definition:</b> NRE_Entity.hpp:43</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">NRE::ECS::View::Iterator</a></div><div class="ttdoc">A basic view iterator. </div><div class="ttdef"><b>Definition:</b> NRE_View.hpp:42</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_php_a0d91d3b3bbb90886dc8dd8ebbab33281"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view.php#a0d91d3b3bbb90886dc8dd8ebbab33281">NRE::ECS::View::end</a></div><div class="ttdeci">Iterator end()</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_php_a8906736592a8a124b6bf6d781416a422"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view.php#a8906736592a8a124b6bf6d781416a422">NRE::ECS::View::begin</a></div><div class="ttdeci">Iterator begin()</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_entity_manager_php_af55ac31ee3c7cb0bcd8e26ccb26b5868"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">NRE::ECS::EntityManager::ComponentMask</a></div><div class="ttdeci">std::bitset&lt; AbstractComponent::MAX_COMPONENTS &gt; ComponentMask</div><div class="ttdef"><b>Definition:</b> NRE_EntityManager.hpp:52</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_php_abbd9b374abea285a601d449234cacb46"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view.php#abbd9b374abea285a601d449234cacb46">NRE::ECS::View::~View</a></div><div class="ttdeci">virtual ~View()=default</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_iterator_php_a6a59facd435e716218c86772453f5a08"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a6a59facd435e716218c86772453f5a08">NRE::ECS::ViewIterator::next</a></div><div class="ttdeci">void next()</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_php_afd2527c49829479e17b435651eabd008"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view.php#afd2527c49829479e17b435651eabd008">NRE::ECS::View::View</a></div><div class="ttdeci">View()</div></div>
<div class="ttc" id="namespace_n_r_e_php_aa87ccdbfdf4cc8a17853dbcbd09cfa18"><div class="ttname"><a href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">NRE::uint32</a></div><div class="ttdeci">std::uint32_t uint32</div><div class="ttdef"><b>Definition:</b> NRE_Id.hpp:22</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator_php_a05a6e24deb9055cc81ef965bdc78a9c1"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php#a05a6e24deb9055cc81ef965bdc78a9c1">NRE::ECS::View::Iterator::Iterator</a></div><div class="ttdeci">Iterator(EntityManager::ComponentMask const m, uint32 i)</div><div class="ttdef"><b>Definition:</b> NRE_View.hpp:54</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
