<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: /mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/Allocator/NRE_AbstractAllocator.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_b1a122bf62c958266ec5bf64d14fde5a.php">ECS</a></li><li class="navelem"><a class="el" href="dir_b3425cf3684a72a972685eae55fae74b.php">Entity</a></li><li class="navelem"><a class="el" href="dir_506b361a64b5c3fb8c72eb8d6abb6c67.php">Manager</a></li><li class="navelem"><a class="el" href="dir_1909940746abd86c0c599cf3ad621065.php">Allocator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_AbstractAllocator.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___abstract_allocator_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_e_c_s.php">ECS</a> {</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;</div><div class="line"><a name="l00027"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">   27</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">AbstractAllocator</a> {</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;                <span class="keyword">public</span> : <span class="comment">// Methods</span></div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ab09e93c356c000b4e34e8065179e925d">AbstractAllocator</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                </div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                    <span class="comment">//## Copy-Constructor ##//</span></div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ab09e93c356c000b4e34e8065179e925d">AbstractAllocator</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">AbstractAllocator</a> <span class="keyword">const</span>&amp; a) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#a8111a5f8f6de47dca57226cec030fc1c">~AbstractAllocator</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ab57d6984b24d9273c5e94dca76012306">expand</a>(std::size_t newSize) = 0;</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;                    <span class="comment">//## Assignment Operator ##//</span></div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">AbstractAllocator</a>&amp; <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#a4c933c62bc9086925115634d44ee8fae">operator =</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">AbstractAllocator</a> <span class="keyword">const</span>&amp; a) = <span class="keyword">delete</span>;</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;            };</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;        }</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;    }</div><div class="ttc" id="namespace_e_c_s_php"><div class="ttname"><a href="namespace_e_c_s.php">ECS</a></div><div class="ttdoc">ECS&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator_php_a4c933c62bc9086925115634d44ee8fae"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#a4c933c62bc9086925115634d44ee8fae">NRE::ECS::AbstractAllocator::operator=</a></div><div class="ttdeci">AbstractAllocator &amp; operator=(AbstractAllocator const &amp;a)=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">NRE::ECS::AbstractAllocator</a></div><div class="ttdoc">An abstract allocator used in the ECS for component pool. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractAllocator.hpp:27</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator_php_ab09e93c356c000b4e34e8065179e925d"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ab09e93c356c000b4e34e8065179e925d">NRE::ECS::AbstractAllocator::AbstractAllocator</a></div><div class="ttdeci">AbstractAllocator()=default</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator_php_a8111a5f8f6de47dca57226cec030fc1c"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#a8111a5f8f6de47dca57226cec030fc1c">NRE::ECS::AbstractAllocator::~AbstractAllocator</a></div><div class="ttdeci">virtual ~AbstractAllocator()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator_php_ab57d6984b24d9273c5e94dca76012306"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ab57d6984b24d9273c5e94dca76012306">NRE::ECS::AbstractAllocator::expand</a></div><div class="ttdeci">virtual void expand(std::size_t newSize)=0</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
