<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: /mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/Iterator/View/Typed/NRE_TypedView.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_b1a122bf62c958266ec5bf64d14fde5a.php">ECS</a></li><li class="navelem"><a class="el" href="dir_b3425cf3684a72a972685eae55fae74b.php">Entity</a></li><li class="navelem"><a class="el" href="dir_506b361a64b5c3fb8c72eb8d6abb6c67.php">Manager</a></li><li class="navelem"><a class="el" href="dir_73723887d630f5da8d29f5a815db9909.php">Iterator</a></li><li class="navelem"><a class="el" href="dir_2538ef0c7acee28898444f7d785a41f8.php">View</a></li><li class="navelem"><a class="el" href="dir_0aff36051a98d313a3bea74a850158f9.php">Typed</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_TypedView.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___typed_view_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">     #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;iostream&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &lt;string&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">    #include &quot;../NRE_View.hpp&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_e_c_s.php">ECS</a> {</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;            <span class="keyword">template</span> &lt;<span class="keywordtype">bool</span> All, <span class="keyword">class </span>... Components&gt;</div><div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php">   33</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php">TypedView</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php">View</a>&lt;All&gt; {</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                <span class="keyword">public</span>:     <span class="comment">//Fields</span></div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;<span class="comment"></span>                    <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity.php">   40</a></span>&#160;                    <span class="keyword">struct </span><a class="code" href="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity.php">identity</a> {</div><div class="line"><a name="l00042"></a><span class="lineno"><a class="line" href="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity.php#afa5c05cf0a83261a6cd65b22f6b34af0">   42</a></span>&#160;                        <span class="keyword">typedef</span> T <a class="code" href="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity.php#afa5c05cf0a83261a6cd65b22f6b34af0">type</a>;</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                    };</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;                <span class="keyword">public</span>:    <span class="comment">// Methods</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php#a537e70f1f4f57a9de131d9874908861c">TypedView</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00055"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php#a8ea6a06a70d8db0277c0b54dfda2bc72">   55</a></span>&#160;                        <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php#a8ea6a06a70d8db0277c0b54dfda2bc72">TypedView</a>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> m) : <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_view.php">View</a>&lt;All&gt;(m) {</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                        }</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00063"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php#a82593603fb0f0b5edc75fcdd697ac373">   63</a></span>&#160;<span class="comment"></span>                        <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php#a82593603fb0f0b5edc75fcdd697ac373">each</a>(<span class="keyword">typename</span> <a class="code" href="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity.php">identity</a>&lt;std::function&lt;<span class="keywordtype">void</span>(<a class="code" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> e, Components&amp; ...)&gt;&gt;::<a class="code" href="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity.php#afa5c05cf0a83261a6cd65b22f6b34af0">type</a> f) {</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;                            <span class="keywordflow">for</span> (<span class="keyword">auto</span> it : *<span class="keyword">this</span>) {</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                                f(it, *(it.template getComponent&lt;Components&gt;().get())...);</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                            }</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;                        }</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;            };</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;        }</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;    }</div><div class="ttc" id="namespace_e_c_s_php"><div class="ttname"><a href="namespace_e_c_s.php">ECS</a></div><div class="ttdoc">ECS&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_typed_view_php_a537e70f1f4f57a9de131d9874908861c"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php#a537e70f1f4f57a9de131d9874908861c">NRE::ECS::TypedView::TypedView</a></div><div class="ttdeci">TypedView()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_view_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_view.php">NRE::ECS::View</a></div><div class="ttdoc">Base view for advanced iterator. </div><div class="ttdef"><b>Definition:</b> NRE_View.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_typed_view_php_a8ea6a06a70d8db0277c0b54dfda2bc72"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php#a8ea6a06a70d8db0277c0b54dfda2bc72">NRE::ECS::TypedView::TypedView</a></div><div class="ttdeci">TypedView(EntityManager::ComponentMask m)</div><div class="ttdef"><b>Definition:</b> NRE_TypedView.hpp:55</div></div>
<div class="ttc" id="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity_php_afa5c05cf0a83261a6cd65b22f6b34af0"><div class="ttname"><a href="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity.php#afa5c05cf0a83261a6cd65b22f6b34af0">NRE::ECS::TypedView::identity::type</a></div><div class="ttdeci">T type</div><div class="ttdef"><b>Definition:</b> NRE_TypedView.hpp:42</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_entity_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_entity.php">NRE::ECS::Entity</a></div><div class="ttdoc">A basic entity. </div><div class="ttdef"><b>Definition:</b> NRE_Entity.hpp:43</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_entity_manager_php_af55ac31ee3c7cb0bcd8e26ccb26b5868"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">NRE::ECS::EntityManager::ComponentMask</a></div><div class="ttdeci">std::bitset&lt; AbstractComponent::MAX_COMPONENTS &gt; ComponentMask</div><div class="ttdef"><b>Definition:</b> NRE_EntityManager.hpp:52</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div></div>
<div class="ttc" id="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity_php"><div class="ttname"><a href="struct_n_r_e_1_1_e_c_s_1_1_typed_view_1_1identity.php">NRE::ECS::TypedView::identity</a></div><div class="ttdoc">Used for meta programming. </div><div class="ttdef"><b>Definition:</b> NRE_TypedView.hpp:40</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_typed_view_php_a82593603fb0f0b5edc75fcdd697ac373"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php#a82593603fb0f0b5edc75fcdd697ac373">NRE::ECS::TypedView::each</a></div><div class="ttdeci">void each(typename identity&lt; std::function&lt; void(Entity e, Components &amp;...)&gt;&gt;::type f)</div><div class="ttdef"><b>Definition:</b> NRE_TypedView.hpp:63</div></div>
<div class="ttc" id="class_n_r_e_1_1_e_c_s_1_1_typed_view_php"><div class="ttname"><a href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php">NRE::ECS::TypedView</a></div><div class="ttdoc">A typed view. </div><div class="ttdef"><b>Definition:</b> NRE_TypedView.hpp:33</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
