<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">EntityManager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::ECS::EntityManager Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ab099ea7136f69f1eb480dcb9ad4357d5">accommodateComponent</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#aef6d714d885257b0bc837858d5c998f7">accommodateEntity</a>(uint32 index)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af1594c65282c219adbc3443068d4c453">assertValid</a>(Id id) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a995b099376b13bf52d832f559acce03e">assign</a>(Id id, Args &amp;&amp;...args)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a> typedef</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#adad32a1d4961d1be9d339082fd4cd9a4">create</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a46cd9e4e5df4a6ec49e5bea55dc63dd1">createId</a>(uint32 index) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a1a35d21c1885d56baa46b385f84425d6">destroy</a>(Id id)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a31ba204064ab3e4e2f155be0eb183d6f">each</a>(class identity&lt; std::function&lt; void(Entity entity, Components &amp;...)&gt;&gt;::type f)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a3f224c7d84dceb9ef237521e2cee50c5">get</a>(Id id)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a4eab64a4ee46dd53f138cb2f543746ad">getCapacity</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a3e3df2957efdee95cf4acaa67e175c88">getComponent</a>(Id id)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ae61acf8c2a308d24d3e5791069230302">getComponent</a>(Id id) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ad7ec67d6ebe9d1cdbbc3e2f8f01c6d87">getComponentCategory</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a685f552096c9217f9dfae113921a132f">getComponentMask</a>(Id id)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ac506af1179180c741dca4e15359381a6">getComponentMask</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a5d9626cfce8872132515ec27782b93c9">getComponentMask</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a92a989a69e89f54e82479e9c8c02972b">getComponentMask</a>(ComponentHandle&lt; T &gt; const &amp;c)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a2bbe46b9d6c697f3fbf903bd6195bcd0">getComponentMask</a>(ComponentHandle&lt; C1 &gt; const &amp;c1, ComponentHandle&lt; Components &gt; const &amp;...args)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a007fa841e2c0fc16232f660287f5aba9">getComponentPtr</a>(Id id)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a26b239ad8c64f639ae7fa5f0a64b1bdb">getComponentPtr</a>(Id id) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a403e46f95f593b89b1fcecd20ccc194d">getComponents</a>(Id id)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ab4f39376993fd01fe1019653eecff67c">getComponents</a>(Id id) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a98dd31691b283d5f279cd70eba70205c">getEntitiesForDebugging</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ae8e13df42fea9ff6278fa86200ae0e6f">getEntitiesWithComponents</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a1c0ae22613dd6c8cda9a15d7600b4712">getEntitiesWithComponents</a>(ComponentHandle&lt; Components &gt; &amp;...components)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ab90ffb0555a2141d9b05e939c26161c0">getEntityComponentMask</a>(uint32 index) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a82368feb5428861132e1f43d601a5f29">getFreeList</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a39ad330a8a8d3cb02368337a097b90df">getSize</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#adf8e9abf557cbe63133a0c3d6e5afedc">hasComponent</a>(Id id) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a12b7718cc6995de3bf7c5d293f9b1080">isValid</a>(Id id) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#aa1f3c73bf14951faff43e3089a3f8d56">remove</a>(Id id)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#aa6bf1bae72de8671f33191113335d02e">reset</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af6999d9fb89c86798f41dcb998b749a9">unpack</a>(Id id, ComponentHandle&lt; T &gt; &amp;a)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a3c482c42b078b856ceb21d16ec89f6b3">unpack</a>(Id id, ComponentHandle&lt; T &gt; &amp;a, ComponentHandle&lt; Args &gt; &amp;...args)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">NRE::ECS::EntityManager</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
