<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::Entity Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_entity-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::Entity Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A basic entity.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_entity.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___entity_8hpp_source.php">NRE_Entity.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a2b2e6bc4dd55b74ee815d8583693286f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a2b2e6bc4dd55b74ee815d8583693286f">Entity</a> ()=default</td></tr>
<tr class="separator:a2b2e6bc4dd55b74ee815d8583693286f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a75f1517d2165eb4528e4f1afb9105099"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a75f1517d2165eb4528e4f1afb9105099">Entity</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> i)</td></tr>
<tr class="separator:a75f1517d2165eb4528e4f1afb9105099"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab1aba9c20a1273c0767bf3d5d380566e"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#ab1aba9c20a1273c0767bf3d5d380566e">Entity</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;e)</td></tr>
<tr class="separator:ab1aba9c20a1273c0767bf3d5d380566e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1c05ca0be3187002194b6810ae49355c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a1c05ca0be3187002194b6810ae49355c">Entity</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> &amp;&amp;e)</td></tr>
<tr class="separator:a1c05ca0be3187002194b6810ae49355c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1a0f2e4b5bb381c4e6368e23a38548e8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a1a0f2e4b5bb381c4e6368e23a38548e8">~Entity</a> ()=default</td></tr>
<tr class="separator:a1a0f2e4b5bb381c4e6368e23a38548e8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2e379f0c42d134e13d42df8eaf85cc05"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a2e379f0c42d134e13d42df8eaf85cc05">isValid</a> () const </td></tr>
<tr class="separator:a2e379f0c42d134e13d42df8eaf85cc05"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2c32fe623b93cd71c8b30d028cb58af4"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a2c32fe623b93cd71c8b30d028cb58af4">getId</a> () const </td></tr>
<tr class="separator:a2c32fe623b93cd71c8b30d028cb58af4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa1d242fd321ebde39150c3d54e068c2b"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:aa1d242fd321ebde39150c3d54e068c2b"><td class="memTemplItemLeft" align="right" valign="top">bool&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#aa1d242fd321ebde39150c3d54e068c2b">hasComponent</a> () const </td></tr>
<tr class="separator:aa1d242fd321ebde39150c3d54e068c2b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5c5ed155fe6280c75e54e10cf9de3e3b"><td class="memTemplParams" colspan="2">template&lt;typename T , typename  = typename std::enable_if&lt;!std::is_const&lt;T&gt;::value&gt;::type&gt; </td></tr>
<tr class="memitem:a5c5ed155fe6280c75e54e10cf9de3e3b"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a5c5ed155fe6280c75e54e10cf9de3e3b">getComponent</a> ()</td></tr>
<tr class="separator:a5c5ed155fe6280c75e54e10cf9de3e3b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a828ddd902ef582d23b1f85c5b9106f09"><td class="memTemplParams" colspan="2">template&lt;typename T , typename  = typename std::enable_if&lt;std::is_const&lt;T&gt;::value&gt;::type&gt; </td></tr>
<tr class="memitem:a828ddd902ef582d23b1f85c5b9106f09"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a828ddd902ef582d23b1f85c5b9106f09">getComponent</a> () const </td></tr>
<tr class="separator:a828ddd902ef582d23b1f85c5b9106f09"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4f6efb87495dec9dbe784b015dff569f"><td class="memTemplParams" colspan="2">template&lt;class... Components&gt; </td></tr>
<tr class="memitem:a4f6efb87495dec9dbe784b015dff569f"><td class="memTemplItemLeft" align="right" valign="top">std::tuple&lt; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Components &gt;... &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a4f6efb87495dec9dbe784b015dff569f">getComponents</a> ()</td></tr>
<tr class="separator:a4f6efb87495dec9dbe784b015dff569f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a28ba1ea4e13823cdffc5b3bfdb5164f4"><td class="memTemplParams" colspan="2">template&lt;class... Components&gt; </td></tr>
<tr class="memitem:a28ba1ea4e13823cdffc5b3bfdb5164f4"><td class="memTemplItemLeft" align="right" valign="top">std::tuple&lt; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; const Components &gt;... &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a28ba1ea4e13823cdffc5b3bfdb5164f4">getComponents</a> () const </td></tr>
<tr class="separator:a28ba1ea4e13823cdffc5b3bfdb5164f4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5d4f1c5419bc0eef29a727aa59714707"><td class="memItemLeft" align="right" valign="top">std::bitset&lt; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_component.php#a2141e882eb37ad59cc4e307ff71c7d0c">AbstractComponent::MAX_COMPONENTS</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a5d4f1c5419bc0eef29a727aa59714707">getComponentMask</a> () const </td></tr>
<tr class="separator:a5d4f1c5419bc0eef29a727aa59714707"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:accd29ef9e581ccd2fcb865f224f362dc"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#accd29ef9e581ccd2fcb865f224f362dc">invalidate</a> ()</td></tr>
<tr class="separator:accd29ef9e581ccd2fcb865f224f362dc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a16fa097fa4d94f27856773dd9319d752"><td class="memTemplParams" colspan="2">template&lt;class T , class... Args&gt; </td></tr>
<tr class="memitem:a16fa097fa4d94f27856773dd9319d752"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a16fa097fa4d94f27856773dd9319d752">assign</a> (Args &amp;&amp;...args)</td></tr>
<tr class="separator:a16fa097fa4d94f27856773dd9319d752"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad91f8d9d92468ed6b46588cb83ad58ce"><td class="memTemplParams" colspan="2">template&lt;class T , class... Args&gt; </td></tr>
<tr class="memitem:ad91f8d9d92468ed6b46588cb83ad58ce"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#ad91f8d9d92468ed6b46588cb83ad58ce">replace</a> (Args &amp;&amp;...args)</td></tr>
<tr class="separator:ad91f8d9d92468ed6b46588cb83ad58ce"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4ca816f2f74ee7c7471ec30d75699e80"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a4ca816f2f74ee7c7471ec30d75699e80"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a4ca816f2f74ee7c7471ec30d75699e80">remove</a> ()</td></tr>
<tr class="separator:a4ca816f2f74ee7c7471ec30d75699e80"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8ca4b547eb670ade4e53012d48ecb588"><td class="memTemplParams" colspan="2">template&lt;class T , class... Args&gt; </td></tr>
<tr class="memitem:a8ca4b547eb670ade4e53012d48ecb588"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a8ca4b547eb670ade4e53012d48ecb588">unpack</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;handle, <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Args &gt; &amp;...args)</td></tr>
<tr class="separator:a8ca4b547eb670ade4e53012d48ecb588"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a56f03804d707d7b9a6acd45944430fd4"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a56f03804d707d7b9a6acd45944430fd4">destroy</a> ()</td></tr>
<tr class="separator:a56f03804d707d7b9a6acd45944430fd4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3e2b4b8a89cbf175fe28f63a0b44470d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a3e2b4b8a89cbf175fe28f63a0b44470d">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;e)=default</td></tr>
<tr class="separator:a3e2b4b8a89cbf175fe28f63a0b44470d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af6cc910c1f8fc86f6e970424c2342377"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#af6cc910c1f8fc86f6e970424c2342377">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> &amp;&amp;e)</td></tr>
<tr class="separator:af6cc910c1f8fc86f6e970424c2342377"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac81d2bb32dc35a5d2a81dace1300303a"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#ac81d2bb32dc35a5d2a81dace1300303a">operator==</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;e) const </td></tr>
<tr class="separator:ac81d2bb32dc35a5d2a81dace1300303a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61f452cca49c74b7ac4ea1a4d6a785ba"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a61f452cca49c74b7ac4ea1a4d6a785ba">operator!=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;e) const </td></tr>
<tr class="separator:a61f452cca49c74b7ac4ea1a4d6a785ba"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac72639ef079144f90236c5a0b59e32c6"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#ac72639ef079144f90236c5a0b59e32c6">operator&lt;</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;e) const </td></tr>
<tr class="separator:ac72639ef079144f90236c5a0b59e32c6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:a71e6784dbeb9d77704cf5b0e201ffdb6"><td class="memItemLeft" align="right" valign="top">static const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php#a71e6784dbeb9d77704cf5b0e201ffdb6">INVALID</a></td></tr>
<tr class="separator:a71e6784dbeb9d77704cf5b0e201ffdb6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A basic entity. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a2b2e6bc4dd55b74ee815d8583693286f"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Entity::Entity </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a75f1517d2165eb4528e4f1afb9105099"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Entity::Entity </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an entity from an id </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ab1aba9c20a1273c0767bf3d5d380566e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Entity::Entity </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Copy e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the entity to copy the content </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a1c05ca0be3187002194b6810ae49355c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Entity::Entity </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move e into this, leaving e empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the entity to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a1a0f2e4b5bb381c4e6368e23a38548e8"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Entity::~Entity </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php" title="A basic entity. ">Entity</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a16fa097fa4d94f27856773dd9319d752"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class... Args&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;T&gt; NRE::ECS::Entity::assign </td>
          <td>(</td>
          <td class="paramtype">Args &amp;&amp;...&#160;</td>
          <td class="paramname"><em>args</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Assign a T component to the entity </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">args</td><td>the component's construction arguments pack </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the newly created component wrapped into an handle </dd></dl>

</div>
</div>
<a class="anchor" id="a56f03804d707d7b9a6acd45944430fd4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::Entity::destroy </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Destroy the entity </p>

</div>
</div>
<a class="anchor" id="a5c5ed155fe6280c75e54e10cf9de3e3b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T , typename  = typename std::enable_if&lt;!std::is_const&lt;T&gt;::value&gt;::type&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;T&gt; NRE::ECS::Entity::getComponent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> getter </p><dl class="section return"><dt>Returns</dt><dd>the T component handle </dd></dl>

</div>
</div>
<a class="anchor" id="a828ddd902ef582d23b1f85c5b9106f09"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T , typename  = typename std::enable_if&lt;std::is_const&lt;T&gt;::value&gt;::type&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;T&gt; NRE::ECS::Entity::getComponent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> getter </p><dl class="section return"><dt>Returns</dt><dd>the T component handle </dd></dl>

</div>
</div>
<a class="anchor" id="a5d4f1c5419bc0eef29a727aa59714707"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::bitset&lt;<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_component.php#a2141e882eb37ad59cc4e307ff71c7d0c">AbstractComponent::MAX_COMPONENTS</a>&gt; NRE::ECS::Entity::getComponentMask </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> mask getter </p><dl class="section return"><dt>Returns</dt><dd>the entity's component mask </dd></dl>

</div>
</div>
<a class="anchor" id="a4f6efb87495dec9dbe784b015dff569f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">std::tuple&lt;<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;Components&gt;...&gt; NRE::ECS::Entity::getComponents </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Components getter </p><dl class="section return"><dt>Returns</dt><dd>all components assigned to the entity </dd></dl>

</div>
</div>
<a class="anchor" id="a28ba1ea4e13823cdffc5b3bfdb5164f4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">std::tuple&lt;<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;const Components&gt;...&gt; NRE::ECS::Entity::getComponents </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Components getter </p><dl class="section return"><dt>Returns</dt><dd>all components assigned to the entity </dd></dl>

</div>
</div>
<a class="anchor" id="a2c32fe623b93cd71c8b30d028cb58af4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const&amp; NRE::ECS::Entity::getId </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php" title="An entity Id. ">Id</a> getter </p><dl class="section return"><dt>Returns</dt><dd>the entity's id </dd></dl>

</div>
</div>
<a class="anchor" id="aa1d242fd321ebde39150c3d54e068c2b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::Entity::hasComponent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Test if the entity is assigned to T component </p><dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="accd29ef9e581ccd2fcb865f224f362dc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::Entity::invalidate </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Invalidate the entity's id </p>

</div>
</div>
<a class="anchor" id="a2e379f0c42d134e13d42df8eaf85cc05"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::Entity::isValid </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Test if the entity is valid </p><dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a61f452cca49c74b7ac4ea1a4d6a785ba"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::Entity::operator!= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Difference test between this and e </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the entity to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="ac72639ef079144f90236c5a0b59e32c6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::Entity::operator&lt; </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Inferior test between this and e </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the entity to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a3e2b4b8a89cbf175fe28f63a0b44470d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a>&amp; NRE::ECS::Entity::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of e into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the entity to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="af6cc910c1f8fc86f6e970424c2342377"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a>&amp; NRE::ECS::Entity::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move assignment of e into this, leaving e empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the entity to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ac81d2bb32dc35a5d2a81dace1300303a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::Entity::operator== </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> const &amp;&#160;</td>
          <td class="paramname"><em>e</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Equality test between this and e </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">e</td><td>the entity to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a4ca816f2f74ee7c7471ec30d75699e80"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::Entity::remove </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Remove a component from the entity </p>

</div>
</div>
<a class="anchor" id="ad91f8d9d92468ed6b46588cb83ad58ce"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class... Args&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;T&gt; NRE::ECS::Entity::replace </td>
          <td>(</td>
          <td class="paramtype">Args &amp;&amp;...&#160;</td>
          <td class="paramname"><em>args</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Replace a component, if it's not assigned, it's assigned </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">args</td><td>the component's construction arguments pack </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the newly created/replaced component wrapped into an handle </dd></dl>

</div>
</div>
<a class="anchor" id="a8ca4b547eb670ade4e53012d48ecb588"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class... Args&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::Entity::unpack </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;&#160;</td>
          <td class="paramname"><em>handle</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Args &gt; &amp;...&#160;</td>
          <td class="paramname"><em>args</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Unpack the entity's components into multiple handles </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">handle</td><td>the component handle to store the first unpacked component </td></tr>
    <tr><td class="paramname">args</td><td>multiple component handles to store the other unpacked components </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="a71e6784dbeb9d77704cf5b0e201ffdb6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> NRE::ECS::Entity::INVALID</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The unique invalid id </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/<a class="el" href="_n_r_e___entity_8hpp_source.php">NRE_Entity.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/NRE_Entity.cpp</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
