<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ab09e93c356c000b4e34e8065179e925d">AbstractAllocator</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">NRE::ECS::AbstractAllocator</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ade93f7c0b1c245406318fdabd9bb5279">AbstractAllocator</a>(AbstractAllocator const &amp;a)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">NRE::ECS::AbstractAllocator</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a08833bbbd37eb8df494fa5f999909648">destroy</a>(std::size_t index)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a94599fc1bb0787e0b8cbb7ac36003c97">expand</a>(std::size_t newSize) override</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a6dc374570a672aa3752035def716b8bc">get</a>(std::size_t index)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#aff5da8e2513007ae755340e9868ba23a">get</a>(std::size_t index) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a6f2636f2c5d11afb62e92b1f363c3dde">operator=</a>(PoolAllocator &amp;&amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#a4c933c62bc9086925115634d44ee8fae">NRE::ECS::AbstractAllocator::operator=</a>(AbstractAllocator const &amp;a)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">NRE::ECS::AbstractAllocator</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a7ff318f139d6c822e13ba08fbd9f3423">PoolAllocator</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#ad71e53019fa97e6a5de6a0504500b123">PoolAllocator</a>(PoolAllocator &amp;&amp;p)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#a8111a5f8f6de47dca57226cec030fc1c">~AbstractAllocator</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">NRE::ECS::AbstractAllocator</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#af033b827ad6aac2f538d1e6e6260a9ab">~PoolAllocator</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
