<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::ECS::ComponentHandle&lt; T &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a00dddf19ba89b879bb17204f9e1e5d32">ComponentHandle</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#aa2d98919a29ff9d14cfec63545786c17">ComponentHandle</a>(Id i)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#accab2b2233017aa9b3602386661e0600">ComponentHandle</a>(ComponentHandle const &amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a48a1bd9720da72ff0d9fc8e0389798a6">ComponentHandle</a>(ComponentHandle &amp;&amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#aaff24cd36b5ba64bdb423dbda505f14e">get</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#ad93cb79ba7e5b3cb7de2269edbe7b419">get</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a73ccdb988ec3e1650a400453342195a1">getEntity</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a350060d2d89dc0c41cf1e41b454be3c8">isValid</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#ab30e0b8e536aae983d0f5e85e6d61574">operator!=</a>(ComponentHandle&lt; T &gt; const &amp;c) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#aa348815bbd82fabef4d8bb1dfaa15538">operator*</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a2fbd3b4c913ba6eb0f571550fa798249">operator*</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a772bbe031edb94c97c25172b1813b3fc">operator-&gt;</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a755fa367e9a27bfd3c2a89f736dd8721">operator-&gt;</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a391825c9b6a1fd97d541fe71ccc7498d">operator=</a>(ComponentHandle&lt; T &gt; const &amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#afed5aaaeeb89d4944897c6ad1154cfb4">operator=</a>(ComponentHandle&lt; T &gt; &amp;&amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#ad48c56cf8b592762487cd839e4edbfda">operator==</a>(ComponentHandle&lt; T &gt; const &amp;c) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#aa1dfaa9f726a3dd6afb049b0d5403002">remove</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a844bfff13d1be0fb629f1a9fc353f0e4">~ComponentHandle</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle&lt; T &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
