<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::AbstractSystem Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_abstract_system-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::AbstractSystem Class Reference<span class="mlabels"><span class="mlabel">abstract</span></span></div>  </div>
</div><!--header-->
<div class="contents">

<p>Base class for template system.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___abstract_system_8hpp_source.php">NRE_AbstractSystem.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::ECS::AbstractSystem:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_e_c_s_1_1_abstract_system.png" usemap="#NRE::ECS::AbstractSystem_map" alt=""/>
  <map id="NRE::ECS::AbstractSystem_map" name="NRE::ECS::AbstractSystem_map">
<area href="class_n_r_e_1_1_e_c_s_1_1_system.php" title="Base class for user defined system. " alt="NRE::ECS::System&lt; T &gt;" shape="rect" coords="0,56,201,80"/>
<area href="class_n_r_e_1_1_e_c_s_1_1_system.php" alt="NRE::ECS::System&lt; TestSystem &gt;" shape="rect" coords="211,56,412,80"/>
<area href="class_test_system.php" alt="TestSystem" shape="rect" coords="211,112,412,136"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a41c3f5fea8c82d7f523a040d0d37bfaa"><td class="memItemLeft" align="right" valign="top">typedef std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">Category</a></td></tr>
<tr class="separator:a41c3f5fea8c82d7f523a040d0d37bfaa"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a48351188d1b10db628d40e53fd5f93f0"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a48351188d1b10db628d40e53fd5f93f0">AbstractSystem</a> ()=default</td></tr>
<tr class="separator:a48351188d1b10db628d40e53fd5f93f0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a763567133d627c90fdbbbd54f45bbaa2"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a763567133d627c90fdbbbd54f45bbaa2">AbstractSystem</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a> const &amp;s)=delete</td></tr>
<tr class="separator:a763567133d627c90fdbbbd54f45bbaa2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac6a5722c3a9f0a297c645c980fe9fd9c"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#ac6a5722c3a9f0a297c645c980fe9fd9c">~AbstractSystem</a> ()=default</td></tr>
<tr class="separator:ac6a5722c3a9f0a297c645c980fe9fd9c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad9e357f219f1763f1ad8d11f0671b6bd"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#ad9e357f219f1763f1ad8d11f0671b6bd">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a> const &amp;s)=delete</td></tr>
<tr class="separator:ad9e357f219f1763f1ad8d11f0671b6bd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a328768e73094c65357a2332874240cfe"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a328768e73094c65357a2332874240cfe">configure</a> ()</td></tr>
<tr class="separator:a328768e73094c65357a2332874240cfe"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a562b3acf22f2950cbce95ab457a756ad"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a562b3acf22f2950cbce95ab457a756ad">update</a> ()=0</td></tr>
<tr class="separator:a562b3acf22f2950cbce95ab457a756ad"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:a9f5f3b58fb52edb02a639063b189ecd2"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">Category</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a9f5f3b58fb52edb02a639063b189ecd2">counter</a> = 0</td></tr>
<tr class="separator:a9f5f3b58fb52edb02a639063b189ecd2"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Base class for template system. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="a41c3f5fea8c82d7f523a040d0d37bfaa"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typedef std::size_t <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">NRE::ECS::AbstractSystem::Category</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Shortcut to hide the Category type </p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a48351188d1b10db628d40e53fd5f93f0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::AbstractSystem::AbstractSystem </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a763567133d627c90fdbbbd54f45bbaa2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::AbstractSystem::AbstractSystem </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a> const &amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the abstract system to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ac6a5722c3a9f0a297c645c980fe9fd9c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual NRE::ECS::AbstractSystem::~AbstractSystem </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php" title="Base class for template system. ">AbstractSystem</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a328768e73094c65357a2332874240cfe"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void NRE::ECS::AbstractSystem::configure </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Configure the system, called once before any rendering or update </p>

</div>
</div>
<a class="anchor" id="ad9e357f219f1763f1ad8d11f0671b6bd"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a>&amp; NRE::ECS::AbstractSystem::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a> const &amp;&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">s</td><td>the abstract system to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a562b3acf22f2950cbce95ab457a756ad"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void NRE::ECS::AbstractSystem::update </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Update the system </p>

<p>Implemented in <a class="el" href="class_test_system.php#ac4f721d9d19f9cedffe5f2232cf0f102">TestSystem</a>.</p>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="a9f5f3b58fb52edb02a639063b189ecd2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">AbstractSystem::Category</a> NRE::ECS::AbstractSystem::counter = 0</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The category counter </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/System/<a class="el" href="_n_r_e___abstract_system_8hpp_source.php">NRE_AbstractSystem.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/System/NRE_AbstractSystem.cpp</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
