<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::Id Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_id-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::Id Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>An entity <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php" title="An entity Id. ">Id</a>.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_id.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___id_8hpp_source.php">NRE_Id.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aa5d2c551c93988f227d2aa35c4c62f08"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#aa5d2c551c93988f227d2aa35c4c62f08">Id</a> ()</td></tr>
<tr class="separator:aa5d2c551c93988f227d2aa35c4c62f08"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a596bf86ac71f16eb32c72d16de34c88f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a596bf86ac71f16eb32c72d16de34c88f">Id</a> (<a class="el" href="namespace_n_r_e.php#aaabd8e7d9cfeba48def9efc5cb73ef27">uint64</a> i)</td></tr>
<tr class="separator:a596bf86ac71f16eb32c72d16de34c88f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5a7f35a83060baf0cc1f0ba12f2328c4"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a5a7f35a83060baf0cc1f0ba12f2328c4">Id</a> (<a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> index, <a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> version)</td></tr>
<tr class="separator:a5a7f35a83060baf0cc1f0ba12f2328c4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abf5fe48dd9b41e44b13d8535bd205273"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#abf5fe48dd9b41e44b13d8535bd205273">Id</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;i)=default</td></tr>
<tr class="separator:abf5fe48dd9b41e44b13d8535bd205273"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5ee23abe7ef3c2389bf1e2a30f83bbf7"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a5ee23abe7ef3c2389bf1e2a30f83bbf7">Id</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> &amp;&amp;i)=default</td></tr>
<tr class="separator:a5ee23abe7ef3c2389bf1e2a30f83bbf7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6ade0f17fd29b06cd5be97af1bbeac03"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a6ade0f17fd29b06cd5be97af1bbeac03">~Id</a> ()=default</td></tr>
<tr class="separator:a6ade0f17fd29b06cd5be97af1bbeac03"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7abbef77570120cd668c8ea7a53a32ec"><td class="memItemLeft" align="right" valign="top"><a class="el" href="namespace_n_r_e.php#aaabd8e7d9cfeba48def9efc5cb73ef27">uint64</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a7abbef77570120cd668c8ea7a53a32ec">getId</a> () const </td></tr>
<tr class="separator:a7abbef77570120cd668c8ea7a53a32ec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a63b1c5ebf58c54c87576e36625bca56c"><td class="memItemLeft" align="right" valign="top"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a63b1c5ebf58c54c87576e36625bca56c">getIndex</a> () const </td></tr>
<tr class="separator:a63b1c5ebf58c54c87576e36625bca56c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af65965c2545bdd0803e4e3141cc8abf5"><td class="memItemLeft" align="right" valign="top"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#af65965c2545bdd0803e4e3141cc8abf5">getVersion</a> () const </td></tr>
<tr class="separator:af65965c2545bdd0803e4e3141cc8abf5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a312e9a61948a3895d50c278d76457198"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a312e9a61948a3895d50c278d76457198">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;i)=default</td></tr>
<tr class="separator:a312e9a61948a3895d50c278d76457198"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aab7787c47bf173f7bc2cd439c6953eb5"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#aab7787c47bf173f7bc2cd439c6953eb5">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> &amp;&amp;i)=default</td></tr>
<tr class="separator:aab7787c47bf173f7bc2cd439c6953eb5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a57d75c8896bc246cc582488324549e73"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a57d75c8896bc246cc582488324549e73">operator==</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;i) const </td></tr>
<tr class="separator:a57d75c8896bc246cc582488324549e73"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a87bdc21282adae93e7e9a57acfb09f17"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a87bdc21282adae93e7e9a57acfb09f17">operator!=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;i) const </td></tr>
<tr class="separator:a87bdc21282adae93e7e9a57acfb09f17"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a488ce8e54da3d06b98ea5d1204e79871"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php#a488ce8e54da3d06b98ea5d1204e79871">operator&lt;</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;i) const </td></tr>
<tr class="separator:a488ce8e54da3d06b98ea5d1204e79871"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>An entity <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php" title="An entity Id. ">Id</a>. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="aa5d2c551c93988f227d2aa35c4c62f08"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Id::Id </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a596bf86ac71f16eb32c72d16de34c88f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Id::Id </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="namespace_n_r_e.php#aaabd8e7d9cfeba48def9efc5cb73ef27">uint64</a>&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an id from a packed 64 bits id index/version </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the packed id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a5a7f35a83060baf0cc1f0ba12f2328c4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Id::Id </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&#160;</td>
          <td class="paramname"><em>index</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&#160;</td>
          <td class="paramname"><em>version</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct an id from a separated index/version </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the id's index </td></tr>
    <tr><td class="paramname">version</td><td>the id's version </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="abf5fe48dd9b41e44b13d8535bd205273"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Id::Id </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy i into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the id to copy the content </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a5ee23abe7ef3c2389bf1e2a30f83bbf7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Id::Id </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move i into this, leaving i empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the id to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a6ade0f17fd29b06cd5be97af1bbeac03"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::ECS::Id::~Id </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php" title="An entity Id. ">Id</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a7abbef77570120cd668c8ea7a53a32ec"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="namespace_n_r_e.php#aaabd8e7d9cfeba48def9efc5cb73ef27">uint64</a> NRE::ECS::Id::getId </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php" title="An entity Id. ">Id</a> getter </p><dl class="section return"><dt>Returns</dt><dd>the id </dd></dl>

</div>
</div>
<a class="anchor" id="a63b1c5ebf58c54c87576e36625bca56c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> NRE::ECS::Id::getIndex </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Index getter </p><dl class="section return"><dt>Returns</dt><dd>the id's index </dd></dl>

</div>
</div>
<a class="anchor" id="af65965c2545bdd0803e4e3141cc8abf5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> NRE::ECS::Id::getVersion </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Version getter </p><dl class="section return"><dt>Returns</dt><dd>the id's version </dd></dl>

</div>
</div>
<a class="anchor" id="a87bdc21282adae93e7e9a57acfb09f17"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::Id::operator!= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Difference test between this and i </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php" title="An entity Id. ">Id</a> to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a488ce8e54da3d06b98ea5d1204e79871"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::Id::operator&lt; </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Inferior test between this and i </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php" title="An entity Id. ">Id</a> to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a312e9a61948a3895d50c278d76457198"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&amp; NRE::ECS::Id::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of i into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the id to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="aab7787c47bf173f7bc2cd439c6953eb5"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&amp; NRE::ECS::Id::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of i into this, leaving i empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the id to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a57d75c8896bc246cc582488324549e73"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::Id::operator== </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> const &amp;&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Equality test between this and i </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php" title="An entity Id. ">Id</a> to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Id/<a class="el" href="_n_r_e___id_8hpp_source.php">NRE_Id.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
