<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">ViewIterator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::ECS::ViewIterator&lt; T, All &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a6a59facd435e716218c86772453f5a08">next</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a2e5b536dc3b520fa335bdeac5de9a29e">operator!=</a>(T const &amp;rhs) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a8bb27527b0b79690886f9ac1f723bb66">operator*</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#ab30f5339d2b6d8bc054e3b551997dd3c">operator*</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a602c15071a7c8e439917b1748d32c861">operator++</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a1831ae17abb095e7d65c71f254a6a83e">operator==</a>(T const &amp;rhs) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a272be19d31f3f6ea28e8e8a7916ee6ff">predicate</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#ab21d102dfe4f120918069a9ff0f17b86">validEntity</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9701e377e9c70c6d842ce09c08280c78">ViewIterator</a>()=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#af43c19a99db764dae3629913bf5f6185">ViewIterator</a>(uint32 i)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#ac2f7faf9980bb487895cfb66e5bc4ddb">ViewIterator</a>(EntityManager::ComponentMask const m, uint32 i)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9073e325fd31867c1e849521de1298bc">~ViewIterator</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator&lt; T, All &gt;</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
