<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::UnpackingView&lt; Components &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">UnpackingView</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::UnpackingView&lt; Components &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A view iterator with unpacking manner.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___unpacking_view_8hpp_source.php">NRE_UnpackingView.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php">Iterator</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A view iterator used to wrap the unpacker behavior.  <a href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_unpacker.php">Unpacker</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Used to unpack a tuple.  <a href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_unpacker.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ad6a6d0402313ba5e1eb63ca59cb24017"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php#ad6a6d0402313ba5e1eb63ca59cb24017">UnpackingView</a> ()=delete</td></tr>
<tr class="separator:ad6a6d0402313ba5e1eb63ca59cb24017"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8f1833a1fd23f1aea894da769450f9fa"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php#a8f1833a1fd23f1aea894da769450f9fa">UnpackingView</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> m, <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Components &gt; &amp;...h)</td></tr>
<tr class="separator:a8f1833a1fd23f1aea894da769450f9fa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9df8d05bd92e5929d1424e269fe72ec4"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php#a9df8d05bd92e5929d1424e269fe72ec4">begin</a> ()</td></tr>
<tr class="separator:a9df8d05bd92e5929d1424e269fe72ec4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a102d3a2f83eab0c6bdcbd5aeba138d56"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php">Iterator</a> const&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php#a102d3a2f83eab0c6bdcbd5aeba138d56">begin</a> () const </td></tr>
<tr class="separator:a102d3a2f83eab0c6bdcbd5aeba138d56"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a140aba89e3ecbc8aaefccfb172eb3a50"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php#a140aba89e3ecbc8aaefccfb172eb3a50">end</a> ()</td></tr>
<tr class="separator:a140aba89e3ecbc8aaefccfb172eb3a50"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6028f06f82b774c3d180b90434d1bcf3"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php">Iterator</a> const&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php#a6028f06f82b774c3d180b90434d1bcf3">end</a> () const </td></tr>
<tr class="separator:a6028f06f82b774c3d180b90434d1bcf3"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class... Components&gt;<br />
class NRE::ECS::UnpackingView&lt; Components &gt;</h3>

<p>A view iterator with unpacking manner. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ad6a6d0402313ba5e1eb63ca59cb24017"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">NRE::ECS::UnpackingView</a>&lt; Components &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">UnpackingView</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="a8f1833a1fd23f1aea894da769450f9fa"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">NRE::ECS::UnpackingView</a>&lt; Components &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">UnpackingView</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a>&#160;</td>
          <td class="paramname"><em>m</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Components &gt; &amp;...&#160;</td>
          <td class="paramname"><em>h</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct an unpacking view from a component mask and a set of component handles </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">m</td><td>the entity's component mask </td></tr>
    <tr><td class="paramname">h</td><td>the component handles pack </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a9df8d05bd92e5929d1424e269fe72ec4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php">Iterator</a> <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">NRE::ECS::UnpackingView</a>&lt; Components &gt;::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Begin iterator </p><dl class="section return"><dt>Returns</dt><dd>an iterator on the begin </dd></dl>

</div>
</div>
<a class="anchor" id="a102d3a2f83eab0c6bdcbd5aeba138d56"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php">Iterator</a> const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">NRE::ECS::UnpackingView</a>&lt; Components &gt;::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Const Begin iterator </p><dl class="section return"><dt>Returns</dt><dd>an iterator on the begin </dd></dl>

</div>
</div>
<a class="anchor" id="a140aba89e3ecbc8aaefccfb172eb3a50"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php">Iterator</a> <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">NRE::ECS::UnpackingView</a>&lt; Components &gt;::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>End iterator </p><dl class="section return"><dt>Returns</dt><dd>an iterator on the end </dd></dl>

</div>
</div>
<a class="anchor" id="a6028f06f82b774c3d180b90434d1bcf3"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view_1_1_iterator.php">Iterator</a> const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">NRE::ECS::UnpackingView</a>&lt; Components &gt;::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Const End iterator </p><dl class="section return"><dt>Returns</dt><dd>an iterator on the end </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/Iterator/View/Unpacking/<a class="el" href="_n_r_e___unpacking_view_8hpp_source.php">NRE_UnpackingView.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
