<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::ComponentHandle&lt; T &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_component_handle-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::ComponentHandle&lt; T &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>class helper to handle access to a component  
 <a href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___component_handle_8hpp_source.php">NRE_ComponentHandle.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a00dddf19ba89b879bb17204f9e1e5d32"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a00dddf19ba89b879bb17204f9e1e5d32">ComponentHandle</a> ()=default</td></tr>
<tr class="separator:a00dddf19ba89b879bb17204f9e1e5d32"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa2d98919a29ff9d14cfec63545786c17"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#aa2d98919a29ff9d14cfec63545786c17">ComponentHandle</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> i)</td></tr>
<tr class="separator:aa2d98919a29ff9d14cfec63545786c17"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:accab2b2233017aa9b3602386661e0600"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#accab2b2233017aa9b3602386661e0600">ComponentHandle</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a> const &amp;c)=default</td></tr>
<tr class="separator:accab2b2233017aa9b3602386661e0600"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a48a1bd9720da72ff0d9fc8e0389798a6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a48a1bd9720da72ff0d9fc8e0389798a6">ComponentHandle</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a> &amp;&amp;c)=default</td></tr>
<tr class="separator:a48a1bd9720da72ff0d9fc8e0389798a6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a844bfff13d1be0fb629f1a9fc353f0e4"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a844bfff13d1be0fb629f1a9fc353f0e4">~ComponentHandle</a> ()=default</td></tr>
<tr class="separator:a844bfff13d1be0fb629f1a9fc353f0e4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a350060d2d89dc0c41cf1e41b454be3c8"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a350060d2d89dc0c41cf1e41b454be3c8">isValid</a> () const </td></tr>
<tr class="separator:a350060d2d89dc0c41cf1e41b454be3c8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaff24cd36b5ba64bdb423dbda505f14e"><td class="memItemLeft" align="right" valign="top">T *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#aaff24cd36b5ba64bdb423dbda505f14e">get</a> ()</td></tr>
<tr class="separator:aaff24cd36b5ba64bdb423dbda505f14e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad93cb79ba7e5b3cb7de2269edbe7b419"><td class="memItemLeft" align="right" valign="top">const T *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#ad93cb79ba7e5b3cb7de2269edbe7b419">get</a> () const </td></tr>
<tr class="separator:ad93cb79ba7e5b3cb7de2269edbe7b419"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a73ccdb988ec3e1650a400453342195a1"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a73ccdb988ec3e1650a400453342195a1">getEntity</a> ()</td></tr>
<tr class="separator:a73ccdb988ec3e1650a400453342195a1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa1dfaa9f726a3dd6afb049b0d5403002"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#aa1dfaa9f726a3dd6afb049b0d5403002">remove</a> ()</td></tr>
<tr class="separator:aa1dfaa9f726a3dd6afb049b0d5403002"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a772bbe031edb94c97c25172b1813b3fc"><td class="memItemLeft" align="right" valign="top">T *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a772bbe031edb94c97c25172b1813b3fc">operator-&gt;</a> ()</td></tr>
<tr class="separator:a772bbe031edb94c97c25172b1813b3fc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a755fa367e9a27bfd3c2a89f736dd8721"><td class="memItemLeft" align="right" valign="top">const T *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a755fa367e9a27bfd3c2a89f736dd8721">operator-&gt;</a> () const </td></tr>
<tr class="separator:a755fa367e9a27bfd3c2a89f736dd8721"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa348815bbd82fabef4d8bb1dfaa15538"><td class="memItemLeft" align="right" valign="top">T &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#aa348815bbd82fabef4d8bb1dfaa15538">operator*</a> ()</td></tr>
<tr class="separator:aa348815bbd82fabef4d8bb1dfaa15538"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2fbd3b4c913ba6eb0f571550fa798249"><td class="memItemLeft" align="right" valign="top">T const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a2fbd3b4c913ba6eb0f571550fa798249">operator*</a> () const </td></tr>
<tr class="separator:a2fbd3b4c913ba6eb0f571550fa798249"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a391825c9b6a1fd97d541fe71ccc7498d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#a391825c9b6a1fd97d541fe71ccc7498d">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; const &amp;c)=default</td></tr>
<tr class="separator:a391825c9b6a1fd97d541fe71ccc7498d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afed5aaaeeb89d4944897c6ad1154cfb4"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#afed5aaaeeb89d4944897c6ad1154cfb4">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;&amp;c)=default</td></tr>
<tr class="separator:afed5aaaeeb89d4944897c6ad1154cfb4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad48c56cf8b592762487cd839e4edbfda"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#ad48c56cf8b592762487cd839e4edbfda">operator==</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; const &amp;c) const </td></tr>
<tr class="separator:ad48c56cf8b592762487cd839e4edbfda"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab30e0b8e536aae983d0f5e85e6d61574"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php#ab30e0b8e536aae983d0f5e85e6d61574">operator!=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; const &amp;c) const </td></tr>
<tr class="separator:ab30e0b8e536aae983d0f5e85e6d61574"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T&gt;<br />
class NRE::ECS::ComponentHandle&lt; T &gt;</h3>

<p>class helper to handle access to a component </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a00dddf19ba89b879bb17204f9e1e5d32"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default Constructor </p>

</div>
</div>
<a class="anchor" id="aa2d98919a29ff9d14cfec63545786c17"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a component handle with it's parent's id </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the parent entity's id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="accab2b2233017aa9b3602386661e0600"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy c into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the component handle to copy the content </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a48a1bd9720da72ff0d9fc8e0389798a6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move c into this, leaving c empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the component handle to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a844bfff13d1be0fb629f1a9fc353f0e4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::~<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php" title="class helper to handle access to a component ">ComponentHandle</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="aaff24cd36b5ba64bdb423dbda505f14e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T* <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::get </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> getter </p><dl class="section return"><dt>Returns</dt><dd>the handled component </dd></dl>

</div>
</div>
<a class="anchor" id="ad93cb79ba7e5b3cb7de2269edbe7b419"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">const T* <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::get </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> getter </p><dl class="section return"><dt>Returns</dt><dd>the handled component </dd></dl>

</div>
</div>
<a class="anchor" id="a73ccdb988ec3e1650a400453342195a1"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::getEntity </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Parent getter </p><dl class="section return"><dt>Returns</dt><dd>the parent entity </dd></dl>

</div>
</div>
<a class="anchor" id="a350060d2d89dc0c41cf1e41b454be3c8"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::isValid </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Test if the parent entity is valid </p><dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="ab30e0b8e536aae983d0f5e85e6d61574"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::operator!= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Difference test between this and c </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the component handle to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="aa348815bbd82fabef4d8bb1dfaa15538"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T&amp; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::operator* </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Dot dereference operator </p><dl class="section return"><dt>Returns</dt><dd>a reference on the handle component </dd></dl>

</div>
</div>
<a class="anchor" id="a2fbd3b4c913ba6eb0f571550fa798249"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T const&amp; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::operator* </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Dot dereference operator </p><dl class="section return"><dt>Returns</dt><dd>a reference on the handle component </dd></dl>

</div>
</div>
<a class="anchor" id="a772bbe031edb94c97c25172b1813b3fc"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T* <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::operator-&gt; </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Arrow dereference operator </p><dl class="section return"><dt>Returns</dt><dd>a pointer on the handle component </dd></dl>

</div>
</div>
<a class="anchor" id="a755fa367e9a27bfd3c2a89f736dd8721"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">const T* <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::operator-&gt; </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Arrow dereference operator </p><dl class="section return"><dt>Returns</dt><dd>a pointer on the handle component </dd></dl>

</div>
</div>
<a class="anchor" id="a391825c9b6a1fd97d541fe71ccc7498d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;T&gt;&amp; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assignment of c into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the component handle to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="afed5aaaeeb89d4944897c6ad1154cfb4"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;T&gt;&amp; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assignment of c into this, leaving c empty </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the component handle to move into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ad48c56cf8b592762487cd839e4edbfda"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::operator== </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Equality test between this and c </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the component handle to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="aa1dfaa9f726a3dd6afb049b0d5403002"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">NRE::ECS::ComponentHandle</a>&lt; T &gt;::remove </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Remove the component from the parent entity </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Component/Handle/<a class="el" href="_n_r_e___component_handle_8hpp_source.php">NRE_ComponentHandle.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
