<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::EntityManager Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php">EntityManager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_entity_manager-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::EntityManager Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php" title="A basic entity. ">Entity</a> creation &amp; component assignment.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___entity_manager_8hpp_source.php">NRE_EntityManager.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::ECS::EntityManager:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_e_c_s_1_1_entity_manager.png" usemap="#NRE::ECS::EntityManager_map" alt=""/>
  <map id="NRE::ECS::EntityManager_map" name="NRE::ECS::EntityManager_map">
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="struct_n_r_e_1_1_e_c_s_1_1_entity_manager_1_1identity.php">identity</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Used for meta programming.  <a href="struct_n_r_e_1_1_e_c_s_1_1_entity_manager_1_1identity.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:af55ac31ee3c7cb0bcd8e26ccb26b5868"><td class="memItemLeft" align="right" valign="top">typedef std::bitset&lt; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_component.php#a2141e882eb37ad59cc4e307ff71c7d0c">AbstractComponent::MAX_COMPONENTS</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a></td></tr>
<tr class="separator:af55ac31ee3c7cb0bcd8e26ccb26b5868"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a82368feb5428861132e1f43d601a5f29"><td class="memItemLeft" align="right" valign="top">Utility::Vector&lt; <a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> &gt; &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a82368feb5428861132e1f43d601a5f29">getFreeList</a> ()</td></tr>
<tr class="separator:a82368feb5428861132e1f43d601a5f29"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab90ffb0555a2141d9b05e939c26161c0"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a> const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ab90ffb0555a2141d9b05e939c26161c0">getEntityComponentMask</a> (<a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> index) const </td></tr>
<tr class="separator:ab90ffb0555a2141d9b05e939c26161c0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a39ad330a8a8d3cb02368337a097b90df"><td class="memItemLeft" align="right" valign="top">std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a39ad330a8a8d3cb02368337a097b90df">getSize</a> () const </td></tr>
<tr class="separator:a39ad330a8a8d3cb02368337a097b90df"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4eab64a4ee46dd53f138cb2f543746ad"><td class="memItemLeft" align="right" valign="top">std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a4eab64a4ee46dd53f138cb2f543746ad">getCapacity</a> () const </td></tr>
<tr class="separator:a4eab64a4ee46dd53f138cb2f543746ad"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3f224c7d84dceb9ef237521e2cee50c5"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a3f224c7d84dceb9ef237521e2cee50c5">get</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id)</td></tr>
<tr class="separator:a3f224c7d84dceb9ef237521e2cee50c5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adf8e9abf557cbe63133a0c3d6e5afedc"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:adf8e9abf557cbe63133a0c3d6e5afedc"><td class="memTemplItemLeft" align="right" valign="top">bool&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#adf8e9abf557cbe63133a0c3d6e5afedc">hasComponent</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id) const </td></tr>
<tr class="separator:adf8e9abf557cbe63133a0c3d6e5afedc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3e3df2957efdee95cf4acaa67e175c88"><td class="memTemplParams" colspan="2">template&lt;typename T , typename  = typename std::enable_if&lt;!std::is_const&lt;T&gt;::value&gt;::type&gt; </td></tr>
<tr class="memitem:a3e3df2957efdee95cf4acaa67e175c88"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a3e3df2957efdee95cf4acaa67e175c88">getComponent</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id)</td></tr>
<tr class="separator:a3e3df2957efdee95cf4acaa67e175c88"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae61acf8c2a308d24d3e5791069230302"><td class="memTemplParams" colspan="2">template&lt;typename T , typename  = typename std::enable_if&lt;std::is_const&lt;T&gt;::value&gt;::type&gt; </td></tr>
<tr class="memitem:ae61acf8c2a308d24d3e5791069230302"><td class="memTemplItemLeft" align="right" valign="top">const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ae61acf8c2a308d24d3e5791069230302">getComponent</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id) const </td></tr>
<tr class="separator:ae61acf8c2a308d24d3e5791069230302"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a403e46f95f593b89b1fcecd20ccc194d"><td class="memTemplParams" colspan="2">template&lt;class... Components&gt; </td></tr>
<tr class="memitem:a403e46f95f593b89b1fcecd20ccc194d"><td class="memTemplItemLeft" align="right" valign="top">std::tuple&lt; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Components &gt;... &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a403e46f95f593b89b1fcecd20ccc194d">getComponents</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id)</td></tr>
<tr class="separator:a403e46f95f593b89b1fcecd20ccc194d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab4f39376993fd01fe1019653eecff67c"><td class="memTemplParams" colspan="2">template&lt;class... Components&gt; </td></tr>
<tr class="memitem:ab4f39376993fd01fe1019653eecff67c"><td class="memTemplItemLeft" align="right" valign="top">std::tuple&lt; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; const Components &gt;... &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ab4f39376993fd01fe1019653eecff67c">getComponents</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id) const </td></tr>
<tr class="separator:ab4f39376993fd01fe1019653eecff67c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a98dd31691b283d5f279cd70eba70205c"><td class="memItemLeft" align="right" valign="top"><a class="el" href="_n_r_e___entity_manager_8hpp.php#af0edcfb37e568a1e4044d830f4f88fa3">DebugView</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a98dd31691b283d5f279cd70eba70205c">getEntitiesForDebugging</a> ()</td></tr>
<tr class="separator:a98dd31691b283d5f279cd70eba70205c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a007fa841e2c0fc16232f660287f5aba9"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a007fa841e2c0fc16232f660287f5aba9"><td class="memTemplItemLeft" align="right" valign="top">T *&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a007fa841e2c0fc16232f660287f5aba9">getComponentPtr</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id)</td></tr>
<tr class="separator:a007fa841e2c0fc16232f660287f5aba9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a26b239ad8c64f639ae7fa5f0a64b1bdb"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a26b239ad8c64f639ae7fa5f0a64b1bdb"><td class="memTemplItemLeft" align="right" valign="top">const T *&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a26b239ad8c64f639ae7fa5f0a64b1bdb">getComponentPtr</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id) const </td></tr>
<tr class="separator:a26b239ad8c64f639ae7fa5f0a64b1bdb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a685f552096c9217f9dfae113921a132f"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a685f552096c9217f9dfae113921a132f">getComponentMask</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id)</td></tr>
<tr class="separator:a685f552096c9217f9dfae113921a132f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac506af1179180c741dca4e15359381a6"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:ac506af1179180c741dca4e15359381a6"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a>&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ac506af1179180c741dca4e15359381a6">getComponentMask</a> ()</td></tr>
<tr class="separator:ac506af1179180c741dca4e15359381a6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5d9626cfce8872132515ec27782b93c9"><td class="memTemplParams" colspan="2">template&lt;class C1 , class C2 , class... Components&gt; </td></tr>
<tr class="memitem:a5d9626cfce8872132515ec27782b93c9"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a>&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a5d9626cfce8872132515ec27782b93c9">getComponentMask</a> ()</td></tr>
<tr class="separator:a5d9626cfce8872132515ec27782b93c9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a92a989a69e89f54e82479e9c8c02972b"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a92a989a69e89f54e82479e9c8c02972b"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a>&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a92a989a69e89f54e82479e9c8c02972b">getComponentMask</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; const &amp;c)</td></tr>
<tr class="separator:a92a989a69e89f54e82479e9c8c02972b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2bbe46b9d6c697f3fbf903bd6195bcd0"><td class="memTemplParams" colspan="2">template&lt;class C1 , class... Components&gt; </td></tr>
<tr class="memitem:a2bbe46b9d6c697f3fbf903bd6195bcd0"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a>&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a2bbe46b9d6c697f3fbf903bd6195bcd0">getComponentMask</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; C1 &gt; const &amp;c1, <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Components &gt; const &amp;...args)</td></tr>
<tr class="separator:a2bbe46b9d6c697f3fbf903bd6195bcd0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a12b7718cc6995de3bf7c5d293f9b1080"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a12b7718cc6995de3bf7c5d293f9b1080">isValid</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id) const </td></tr>
<tr class="separator:a12b7718cc6995de3bf7c5d293f9b1080"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adad32a1d4961d1be9d339082fd4cd9a4"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#adad32a1d4961d1be9d339082fd4cd9a4">create</a> ()</td></tr>
<tr class="separator:adad32a1d4961d1be9d339082fd4cd9a4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1a35d21c1885d56baa46b385f84425d6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a1a35d21c1885d56baa46b385f84425d6">destroy</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id)</td></tr>
<tr class="separator:a1a35d21c1885d56baa46b385f84425d6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a46cd9e4e5df4a6ec49e5bea55dc63dd1"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a46cd9e4e5df4a6ec49e5bea55dc63dd1">createId</a> (<a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> index) const </td></tr>
<tr class="separator:a46cd9e4e5df4a6ec49e5bea55dc63dd1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a995b099376b13bf52d832f559acce03e"><td class="memTemplParams" colspan="2">template&lt;class T , class... Args&gt; </td></tr>
<tr class="memitem:a995b099376b13bf52d832f559acce03e"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a995b099376b13bf52d832f559acce03e">assign</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id, Args &amp;&amp;...args)</td></tr>
<tr class="separator:a995b099376b13bf52d832f559acce03e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa1f3c73bf14951faff43e3089a3f8d56"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:aa1f3c73bf14951faff43e3089a3f8d56"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#aa1f3c73bf14951faff43e3089a3f8d56">remove</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id)</td></tr>
<tr class="separator:aa1f3c73bf14951faff43e3089a3f8d56"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae8e13df42fea9ff6278fa86200ae0e6f"><td class="memTemplParams" colspan="2">template&lt;class... Components&gt; </td></tr>
<tr class="memitem:ae8e13df42fea9ff6278fa86200ae0e6f"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php">TypedView</a>&lt; false, Components... &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ae8e13df42fea9ff6278fa86200ae0e6f">getEntitiesWithComponents</a> ()</td></tr>
<tr class="separator:ae8e13df42fea9ff6278fa86200ae0e6f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1c0ae22613dd6c8cda9a15d7600b4712"><td class="memTemplParams" colspan="2">template&lt;class... Components&gt; </td></tr>
<tr class="memitem:a1c0ae22613dd6c8cda9a15d7600b4712"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">UnpackingView</a>&lt; Components... &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a1c0ae22613dd6c8cda9a15d7600b4712">getEntitiesWithComponents</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Components &gt; &amp;...components)</td></tr>
<tr class="separator:a1c0ae22613dd6c8cda9a15d7600b4712"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a31ba204064ab3e4e2f155be0eb183d6f"><td class="memTemplParams" colspan="2">template&lt;class... Components&gt; </td></tr>
<tr class="memitem:a31ba204064ab3e4e2f155be0eb183d6f"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a31ba204064ab3e4e2f155be0eb183d6f">each</a> (class <a class="el" href="struct_n_r_e_1_1_e_c_s_1_1_entity_manager_1_1identity.php">identity</a>&lt; std::function&lt; void(<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> entity, Components &amp;...)&gt;&gt;::type f)</td></tr>
<tr class="separator:a31ba204064ab3e4e2f155be0eb183d6f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af6999d9fb89c86798f41dcb998b749a9"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:af6999d9fb89c86798f41dcb998b749a9"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af6999d9fb89c86798f41dcb998b749a9">unpack</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id, <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;a)</td></tr>
<tr class="separator:af6999d9fb89c86798f41dcb998b749a9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3c482c42b078b856ceb21d16ec89f6b3"><td class="memTemplParams" colspan="2">template&lt;class T , class... Args&gt; </td></tr>
<tr class="memitem:a3c482c42b078b856ceb21d16ec89f6b3"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#a3c482c42b078b856ceb21d16ec89f6b3">unpack</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id, <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;a, <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Args &gt; &amp;...args)</td></tr>
<tr class="separator:a3c482c42b078b856ceb21d16ec89f6b3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa6bf1bae72de8671f33191113335d02e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#aa6bf1bae72de8671f33191113335d02e">reset</a> ()</td></tr>
<tr class="separator:aa6bf1bae72de8671f33191113335d02e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af1594c65282c219adbc3443068d4c453"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af1594c65282c219adbc3443068d4c453">assertValid</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> id) const </td></tr>
<tr class="separator:af1594c65282c219adbc3443068d4c453"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aef6d714d885257b0bc837858d5c998f7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#aef6d714d885257b0bc837858d5c998f7">accommodateEntity</a> (<a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> index)</td></tr>
<tr class="separator:aef6d714d885257b0bc837858d5c998f7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab099ea7136f69f1eb480dcb9ad4357d5"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:ab099ea7136f69f1eb480dcb9ad4357d5"><td class="memTemplItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a>&lt; T &gt; *&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ab099ea7136f69f1eb480dcb9ad4357d5">accommodateComponent</a> ()</td></tr>
<tr class="separator:ab099ea7136f69f1eb480dcb9ad4357d5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:ad7ec67d6ebe9d1cdbbc3e2f8f01c6d87"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:ad7ec67d6ebe9d1cdbbc3e2f8f01c6d87"><td class="memTemplItemLeft" align="right" valign="top">static <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_component.php#a1197e903d5b51257be54973b2ff1b27f">AbstractComponent::Category</a>&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#ad7ec67d6ebe9d1cdbbc3e2f8f01c6d87">getComponentCategory</a> ()</td></tr>
<tr class="separator:ad7ec67d6ebe9d1cdbbc3e2f8f01c6d87"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php" title="A basic entity. ">Entity</a> creation &amp; component assignment. </p>
</div><h2 class="groupheader">Member Typedef Documentation</h2>
<a class="anchor" id="af55ac31ee3c7cb0bcd8e26ccb26b5868"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">typedef std::bitset&lt;<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_component.php#a2141e882eb37ad59cc4e307ff71c7d0c">AbstractComponent::MAX_COMPONENTS</a>&gt; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">NRE::ECS::EntityManager::ComponentMask</a></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Shortcut to hide the bitset used for component masking </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ab099ea7136f69f1eb480dcb9ad4357d5"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a>&lt;T&gt;* NRE::ECS::EntityManager::accommodateComponent </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Accommodate a component's allocator </p><dl class="section return"><dt>Returns</dt><dd>the component's allocator </dd></dl>

</div>
</div>
<a class="anchor" id="aef6d714d885257b0bc837858d5c998f7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::EntityManager::accommodateEntity </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Accommodate entity from an index </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>an entity's id index </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="af1594c65282c219adbc3443068d4c453"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::EntityManager::assertValid </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Assert if an entity is valid </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a995b099376b13bf52d832f559acce03e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class... Args&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;T&gt; NRE::ECS::EntityManager::assign </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Args &amp;&amp;...&#160;</td>
          <td class="paramname"><em>args</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Assign a T component to an entity </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
    <tr><td class="paramname">args</td><td>the component's construction arguments pack </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the newly created component wrapped into an handle </dd></dl>

</div>
</div>
<a class="anchor" id="adad32a1d4961d1be9d339082fd4cd9a4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> NRE::ECS::EntityManager::create </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Create a new entity </p><dl class="section return"><dt>Returns</dt><dd>the newly created entity </dd></dl>

</div>
</div>
<a class="anchor" id="a46cd9e4e5df4a6ec49e5bea55dc63dd1"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a> NRE::ECS::EntityManager::createId </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Create an entity id from an index </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the id's index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the newly created id </dd></dl>

</div>
</div>
<a class="anchor" id="a1a35d21c1885d56baa46b385f84425d6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::EntityManager::destroy </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Destroy an entity </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a31ba204064ab3e4e2f155be0eb183d6f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::EntityManager::each </td>
          <td>(</td>
          <td class="paramtype">class <a class="el" href="struct_n_r_e_1_1_e_c_s_1_1_entity_manager_1_1identity.php">identity</a>&lt; std::function&lt; void(<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> entity, Components &amp;...)&gt;&gt;::type&#160;</td>
          <td class="paramname"><em>f</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>A for each loop on the typed view element </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">f</td><td>a lambda to apply </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a3f224c7d84dceb9ef237521e2cee50c5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> NRE::ECS::EntityManager::get </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php" title="A basic entity. ">Entity</a> getter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding entity </dd></dl>

</div>
</div>
<a class="anchor" id="a4eab64a4ee46dd53f138cb2f543746ad"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::size_t NRE::ECS::EntityManager::getCapacity </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Capacity getter </p><dl class="section return"><dt>Returns</dt><dd>the manager's entity capacity </dd></dl>

</div>
</div>
<a class="anchor" id="a3e3df2957efdee95cf4acaa67e175c88"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T , typename  = typename std::enable_if&lt;!std::is_const&lt;T&gt;::value&gt;::type&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;T&gt; NRE::ECS::EntityManager::getComponent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> getter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the T component handle </dd></dl>

</div>
</div>
<a class="anchor" id="ae61acf8c2a308d24d3e5791069230302"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T , typename  = typename std::enable_if&lt;std::is_const&lt;T&gt;::value&gt;::type&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;T&gt; NRE::ECS::EntityManager::getComponent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> getter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the T component handle </dd></dl>

</div>
</div>
<a class="anchor" id="ad7ec67d6ebe9d1cdbbc3e2f8f01c6d87"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_component.php#a1197e903d5b51257be54973b2ff1b27f">AbstractComponent::Category</a> NRE::ECS::EntityManager::getComponentCategory </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> category getter </p><dl class="section return"><dt>Returns</dt><dd>a T component category </dd></dl>

</div>
</div>
<a class="anchor" id="a685f552096c9217f9dfae113921a132f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a> NRE::ECS::EntityManager::getComponentMask </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> mask getter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding mask </dd></dl>

</div>
</div>
<a class="anchor" id="ac506af1179180c741dca4e15359381a6"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a> NRE::ECS::EntityManager::getComponentMask </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> mask getter </p><dl class="section return"><dt>Returns</dt><dd>a created mask masked with T component </dd></dl>

</div>
</div>
<a class="anchor" id="a5d9626cfce8872132515ec27782b93c9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class C1 , class C2 , class... Components&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a> NRE::ECS::EntityManager::getComponentMask </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> mask getter </p><dl class="section return"><dt>Returns</dt><dd>a created mask masked with multiple components </dd></dl>

</div>
</div>
<a class="anchor" id="a92a989a69e89f54e82479e9c8c02972b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a> NRE::ECS::EntityManager::getComponentMask </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> mask getter </p><dl class="section return"><dt>Returns</dt><dd>a created mask masked with a component handle type </dd></dl>

</div>
</div>
<a class="anchor" id="a2bbe46b9d6c697f3fbf903bd6195bcd0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class C1 , class... Components&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a> NRE::ECS::EntityManager::getComponentMask </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; C1 &gt; const &amp;&#160;</td>
          <td class="paramname"><em>c1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Components &gt; const &amp;...&#160;</td>
          <td class="paramname"><em>args</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> mask getter </p><dl class="section return"><dt>Returns</dt><dd>a created mask masked with multiple component handles type </dd></dl>

</div>
</div>
<a class="anchor" id="a007fa841e2c0fc16232f660287f5aba9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T* NRE::ECS::EntityManager::getComponentPtr </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> pointer getter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>an entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>a direct pointer on the component </dd></dl>

</div>
</div>
<a class="anchor" id="a26b239ad8c64f639ae7fa5f0a64b1bdb"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">const T* NRE::ECS::EntityManager::getComponentPtr </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> pointer getter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>an entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>a direct pointer on the component </dd></dl>

</div>
</div>
<a class="anchor" id="a403e46f95f593b89b1fcecd20ccc194d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">std::tuple&lt;<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;Components&gt;...&gt; NRE::ECS::EntityManager::getComponents </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Components getter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>all components assigned to the entity </dd></dl>

</div>
</div>
<a class="anchor" id="ab4f39376993fd01fe1019653eecff67c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">std::tuple&lt;<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt;const Components&gt;...&gt; NRE::ECS::EntityManager::getComponents </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Components getter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>all components assigned to the entity </dd></dl>

</div>
</div>
<a class="anchor" id="a98dd31691b283d5f279cd70eba70205c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="_n_r_e___entity_manager_8hpp.php#af0edcfb37e568a1e4044d830f4f88fa3">DebugView</a> NRE::ECS::EntityManager::getEntitiesForDebugging </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Debug view getter </p><dl class="section return"><dt>Returns</dt><dd>a debug view on all entity stored </dd></dl>

</div>
</div>
<a class="anchor" id="ae8e13df42fea9ff6278fa86200ae0e6f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php">TypedView</a>&lt;false, Components...&gt; NRE::ECS::EntityManager::getEntitiesWithComponents </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Typedview getter </p><dl class="section return"><dt>Returns</dt><dd>a typed view on entity with passed components type </dd></dl>

</div>
</div>
<a class="anchor" id="a1c0ae22613dd6c8cda9a15d7600b4712"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class... Components&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_unpacking_view.php">UnpackingView</a>&lt;Components...&gt; NRE::ECS::EntityManager::getEntitiesWithComponents </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Components &gt; &amp;...&#160;</td>
          <td class="paramname"><em>components</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Typedview getter </p><dl class="section return"><dt>Returns</dt><dd>a typed view on entity with passed component handles' type </dd></dl>

</div>
</div>
<a class="anchor" id="ab90ffb0555a2141d9b05e939c26161c0"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">ComponentMask</a> const&amp; NRE::ECS::EntityManager::getEntityComponentMask </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component.php" title="Base component for user defined component. ">Component</a> mask getter </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the mask's index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding mask </dd></dl>

</div>
</div>
<a class="anchor" id="a82368feb5428861132e1f43d601a5f29"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Utility::Vector&lt;<a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&gt;&amp; NRE::ECS::EntityManager::getFreeList </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>FreeList getter </p><dl class="section return"><dt>Returns</dt><dd>the manager's free list </dd></dl>

</div>
</div>
<a class="anchor" id="a39ad330a8a8d3cb02368337a097b90df"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::size_t NRE::ECS::EntityManager::getSize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Size getter </p><dl class="section return"><dt>Returns</dt><dd>the manager's entity number </dd></dl>

</div>
</div>
<a class="anchor" id="adf8e9abf557cbe63133a0c3d6e5afedc"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::EntityManager::hasComponent </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Test if an entity is assigned to T component </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a12b7718cc6995de3bf7c5d293f9b1080"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::ECS::EntityManager::isValid </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Test if an entity is valid </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="aa1f3c73bf14951faff43e3089a3f8d56"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::EntityManager::remove </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Remove a component from an entity </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aa6bf1bae72de8671f33191113335d02e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::EntityManager::reset </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Reset the entity manager </p>

</div>
</div>
<a class="anchor" id="af6999d9fb89c86798f41dcb998b749a9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::EntityManager::unpack </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;&#160;</td>
          <td class="paramname"><em>a</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Unpack an entity's component into an handle </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
    <tr><td class="paramname">a</td><td>the component handle to store the unpacked component </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a3c482c42b078b856ceb21d16ec89f6b3"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class... Args&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::EntityManager::unpack </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_id.php">Id</a>&#160;</td>
          <td class="paramname"><em>id</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; T &gt; &amp;&#160;</td>
          <td class="paramname"><em>a</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_component_handle.php">ComponentHandle</a>&lt; Args &gt; &amp;...&#160;</td>
          <td class="paramname"><em>args</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Unpack an entity's components into multiple handles </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the entity's id </td></tr>
    <tr><td class="paramname">a</td><td>the component handle to store the first unpacked component </td></tr>
    <tr><td class="paramname">args</td><td>multiple component handles to store the other unpacked components </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/<a class="el" href="_n_r_e___entity_manager_8hpp_source.php">NRE_EntityManager.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/NRE_EntityManager.cpp</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
