<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A pool allocator used to manage component in the <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___pool_allocator_8hpp_source.php">NRE_PoolAllocator.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.png" usemap="#NRE::ECS::PoolAllocator_3C_20T_2C_20ChunkSize_20_3E_map" alt=""/>
  <map id="NRE::ECS::PoolAllocator_3C_20T_2C_20ChunkSize_20_3E_map" name="NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;_map">
<area href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php" title="An abstract allocator used in the ECS for component pool. " alt="NRE::ECS::AbstractAllocator" shape="rect" coords="0,0,250,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a7ff318f139d6c822e13ba08fbd9f3423"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a7ff318f139d6c822e13ba08fbd9f3423">PoolAllocator</a> ()</td></tr>
<tr class="separator:a7ff318f139d6c822e13ba08fbd9f3423"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad71e53019fa97e6a5de6a0504500b123"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#ad71e53019fa97e6a5de6a0504500b123">PoolAllocator</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a> &amp;&amp;p)</td></tr>
<tr class="separator:ad71e53019fa97e6a5de6a0504500b123"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af033b827ad6aac2f538d1e6e6260a9ab"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#af033b827ad6aac2f538d1e6e6260a9ab">~PoolAllocator</a> ()</td></tr>
<tr class="separator:af033b827ad6aac2f538d1e6e6260a9ab"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a94599fc1bb0787e0b8cbb7ac36003c97"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a94599fc1bb0787e0b8cbb7ac36003c97">expand</a> (std::size_t newSize) override</td></tr>
<tr class="separator:a94599fc1bb0787e0b8cbb7ac36003c97"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6dc374570a672aa3752035def716b8bc"><td class="memItemLeft" align="right" valign="top">T *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a6dc374570a672aa3752035def716b8bc">get</a> (std::size_t index)</td></tr>
<tr class="separator:a6dc374570a672aa3752035def716b8bc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aff5da8e2513007ae755340e9868ba23a"><td class="memItemLeft" align="right" valign="top">const T *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#aff5da8e2513007ae755340e9868ba23a">get</a> (std::size_t index) const </td></tr>
<tr class="separator:aff5da8e2513007ae755340e9868ba23a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a08833bbbd37eb8df494fa5f999909648"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a08833bbbd37eb8df494fa5f999909648">destroy</a> (std::size_t index)</td></tr>
<tr class="separator:a08833bbbd37eb8df494fa5f999909648"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6f2636f2c5d11afb62e92b1f363c3dde"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php#a6f2636f2c5d11afb62e92b1f363c3dde">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a> &amp;&amp;p)</td></tr>
<tr class="separator:a6f2636f2c5d11afb62e92b1f363c3dde"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">NRE::ECS::AbstractAllocator</a></td></tr>
<tr class="memitem:ab09e93c356c000b4e34e8065179e925d inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ab09e93c356c000b4e34e8065179e925d">AbstractAllocator</a> ()=default</td></tr>
<tr class="separator:ab09e93c356c000b4e34e8065179e925d inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ade93f7c0b1c245406318fdabd9bb5279 inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ade93f7c0b1c245406318fdabd9bb5279">AbstractAllocator</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">AbstractAllocator</a> const &amp;a)=delete</td></tr>
<tr class="separator:ade93f7c0b1c245406318fdabd9bb5279 inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8111a5f8f6de47dca57226cec030fc1c inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#a8111a5f8f6de47dca57226cec030fc1c">~AbstractAllocator</a> ()=default</td></tr>
<tr class="separator:a8111a5f8f6de47dca57226cec030fc1c inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4c933c62bc9086925115634d44ee8fae inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">AbstractAllocator</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#a4c933c62bc9086925115634d44ee8fae">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php">AbstractAllocator</a> const &amp;a)=delete</td></tr>
<tr class="separator:a4c933c62bc9086925115634d44ee8fae inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_allocator"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T, std::size_t ChunkSize = 4096&gt;<br />
class NRE::ECS::PoolAllocator&lt; T, ChunkSize &gt;</h3>

<p>A pool allocator used to manage component in the <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a7ff318f139d6c822e13ba08fbd9f3423"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, std::size_t ChunkSize = 4096&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator</a>&lt; T, ChunkSize &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct the pool allocator </p>

</div>
</div>
<a class="anchor" id="ad71e53019fa97e6a5de6a0504500b123"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, std::size_t ChunkSize = 4096&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator</a>&lt; T, ChunkSize &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a>&lt; T, ChunkSize &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>p</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move p into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">p</td><td>the pool allocator to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="af033b827ad6aac2f538d1e6e6260a9ab"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, std::size_t ChunkSize = 4096&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator</a>&lt; T, ChunkSize &gt;::~<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php" title="A pool allocator used to manage component in the ECS. ">PoolAllocator</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a08833bbbd37eb8df494fa5f999909648"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, std::size_t ChunkSize = 4096&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator</a>&lt; T, ChunkSize &gt;::destroy </td>
          <td>(</td>
          <td class="paramtype">std::size_t&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Destroy an object </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the object index </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a94599fc1bb0787e0b8cbb7ac36003c97"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, std::size_t ChunkSize = 4096&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator</a>&lt; T, ChunkSize &gt;::expand </td>
          <td>(</td>
          <td class="paramtype">std::size_t&#160;</td>
          <td class="paramname"><em>newSize</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Expand the pool in order to accept at least size elements </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">newSize</td><td>the new minimum size </td></tr>
  </table>
  </dd>
</dl>

<p>Implements <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_allocator.php#ab57d6984b24d9273c5e94dca76012306">NRE::ECS::AbstractAllocator</a>.</p>

</div>
</div>
<a class="anchor" id="a6dc374570a672aa3752035def716b8bc"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, std::size_t ChunkSize = 4096&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T* <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator</a>&lt; T, ChunkSize &gt;::get </td>
          <td>(</td>
          <td class="paramtype">std::size_t&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Query an object address </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the object index </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aff5da8e2513007ae755340e9868ba23a"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, std::size_t ChunkSize = 4096&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">const T* <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator</a>&lt; T, ChunkSize &gt;::get </td>
          <td>(</td>
          <td class="paramtype">std::size_t&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Query an object address </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the object index </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a6f2636f2c5d11afb62e92b1f363c3dde"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, std::size_t ChunkSize = 4096&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a>&amp; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">NRE::ECS::PoolAllocator</a>&lt; T, ChunkSize &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_pool_allocator.php">PoolAllocator</a>&lt; T, ChunkSize &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>p</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Move assign p into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">p</td><td>the object to copy into this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/Allocator/<a class="el" href="_n_r_e___pool_allocator_8hpp_source.php">NRE_PoolAllocator.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
