<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::System&lt; T &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system.php">System</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_system-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::System&lt; T &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Base class for user defined system.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_system.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___system_8hpp_source.php">NRE_System.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::ECS::System&lt; T &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_e_c_s_1_1_system.png" usemap="#NRE::ECS::System_3C_20T_20_3E_map" alt=""/>
  <map id="NRE::ECS::System_3C_20T_20_3E_map" name="NRE::ECS::System&lt; T &gt;_map">
<area href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php" title="Base class for template system. " alt="NRE::ECS::AbstractSystem" shape="rect" coords="0,0,161,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a2b894f5b259792fa6c0f743ebd05ee5e"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system.php#a2b894f5b259792fa6c0f743ebd05ee5e">~System</a> ()=default</td></tr>
<tr class="separator:a2b894f5b259792fa6c0f743ebd05ee5e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">NRE::ECS::AbstractSystem</a></td></tr>
<tr class="memitem:a48351188d1b10db628d40e53fd5f93f0 inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a48351188d1b10db628d40e53fd5f93f0">AbstractSystem</a> ()=default</td></tr>
<tr class="separator:a48351188d1b10db628d40e53fd5f93f0 inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a763567133d627c90fdbbbd54f45bbaa2 inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a763567133d627c90fdbbbd54f45bbaa2">AbstractSystem</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a> const &amp;s)=delete</td></tr>
<tr class="separator:a763567133d627c90fdbbbd54f45bbaa2 inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac6a5722c3a9f0a297c645c980fe9fd9c inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#ac6a5722c3a9f0a297c645c980fe9fd9c">~AbstractSystem</a> ()=default</td></tr>
<tr class="separator:ac6a5722c3a9f0a297c645c980fe9fd9c inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad9e357f219f1763f1ad8d11f0671b6bd inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#ad9e357f219f1763f1ad8d11f0671b6bd">operator=</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">AbstractSystem</a> const &amp;s)=delete</td></tr>
<tr class="separator:ad9e357f219f1763f1ad8d11f0671b6bd inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a328768e73094c65357a2332874240cfe inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a328768e73094c65357a2332874240cfe">configure</a> ()</td></tr>
<tr class="separator:a328768e73094c65357a2332874240cfe inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a562b3acf22f2950cbce95ab457a756ad inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a562b3acf22f2950cbce95ab457a756ad">update</a> ()=0</td></tr>
<tr class="separator:a562b3acf22f2950cbce95ab457a756ad inherit pub_methods_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:a8e9d9a9a6ddafa1594bba2a5d860eee2"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">Category</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system.php#a8e9d9a9a6ddafa1594bba2a5d860eee2">getCategory</a> ()</td></tr>
<tr class="separator:a8e9d9a9a6ddafa1594bba2a5d860eee2"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pub_types_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td colspan="2" onclick="javascript:toggleInherit('pub_types_class_n_r_e_1_1_e_c_s_1_1_abstract_system')"><img src="closed.png" alt="-"/>&#160;Public Types inherited from <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">NRE::ECS::AbstractSystem</a></td></tr>
<tr class="memitem:a41c3f5fea8c82d7f523a040d0d37bfaa inherit pub_types_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memItemLeft" align="right" valign="top">typedef std::size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">Category</a></td></tr>
<tr class="separator:a41c3f5fea8c82d7f523a040d0d37bfaa inherit pub_types_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_static_attribs_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td colspan="2" onclick="javascript:toggleInherit('pub_static_attribs_class_n_r_e_1_1_e_c_s_1_1_abstract_system')"><img src="closed.png" alt="-"/>&#160;Static Public Attributes inherited from <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php">NRE::ECS::AbstractSystem</a></td></tr>
<tr class="memitem:a9f5f3b58fb52edb02a639063b189ecd2 inherit pub_static_attribs_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">Category</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a9f5f3b58fb52edb02a639063b189ecd2">counter</a> = 0</td></tr>
<tr class="separator:a9f5f3b58fb52edb02a639063b189ecd2 inherit pub_static_attribs_class_n_r_e_1_1_e_c_s_1_1_abstract_system"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T&gt;<br />
class NRE::ECS::System&lt; T &gt;</h3>

<p>Base class for user defined system. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a2b894f5b259792fa6c0f743ebd05ee5e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system.php">NRE::ECS::System</a>&lt; T &gt;::~<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system.php">System</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system.php" title="Base class for user defined system. ">System</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a8e9d9a9a6ddafa1594bba2a5d860eee2"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_abstract_system.php#a41c3f5fea8c82d7f523a040d0d37bfaa">Category</a> <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system.php">NRE::ECS::System</a>&lt; T &gt;::getCategory </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Category getter </p><dl class="section return"><dt>Returns</dt><dd>the T system category </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/System/<a class="el" href="_n_r_e___system_8hpp_source.php">NRE_System.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
