<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::SystemManager Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php">SystemManager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_system_manager-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::SystemManager Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage system storing and update.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___system_manager_8hpp_source.php">NRE_SystemManager.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::ECS::SystemManager:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_e_c_s_1_1_system_manager.png" usemap="#NRE::ECS::SystemManager_map" alt=""/>
  <map id="NRE::ECS::SystemManager_map" name="NRE::ECS::SystemManager_map">
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a06ba6ff5e300b22f6e392cfb0e75319f"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a06ba6ff5e300b22f6e392cfb0e75319f"><td class="memTemplItemLeft" align="right" valign="top">T *&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a06ba6ff5e300b22f6e392cfb0e75319f">getSystem</a> ()</td></tr>
<tr class="separator:a06ba6ff5e300b22f6e392cfb0e75319f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5df28f5f679e047dfe0a542192896353"><td class="memTemplParams" colspan="2">template&lt;class T , class... Args&gt; </td></tr>
<tr class="memitem:a5df28f5f679e047dfe0a542192896353"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a5df28f5f679e047dfe0a542192896353">add</a> (Args &amp;&amp;...args)</td></tr>
<tr class="separator:a5df28f5f679e047dfe0a542192896353"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a01017c20cc72cd42f54207f0074c4601"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a01017c20cc72cd42f54207f0074c4601"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a01017c20cc72cd42f54207f0074c4601">update</a> ()</td></tr>
<tr class="separator:a01017c20cc72cd42f54207f0074c4601"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af310e9ee3b6e45e4d03dd811392c2546"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#af310e9ee3b6e45e4d03dd811392c2546">updateAll</a> ()</td></tr>
<tr class="separator:af310e9ee3b6e45e4d03dd811392c2546"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a74e8059b19200ac24edd8fe73c2e65b5"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#a74e8059b19200ac24edd8fe73c2e65b5">configure</a> ()</td></tr>
<tr class="separator:a74e8059b19200ac24edd8fe73c2e65b5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:aedfccb1319af97e4663dea87cdd4c3a1"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:aedfccb1319af97e4663dea87cdd4c3a1"><td class="memTemplItemLeft" align="right" valign="top">static T *&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system_manager.php#aedfccb1319af97e4663dea87cdd4c3a1">get</a> ()</td></tr>
<tr class="separator:aedfccb1319af97e4663dea87cdd4c3a1"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage system storing and update. </p>
</div><h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a5df28f5f679e047dfe0a542192896353"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class... Args&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::SystemManager::add </td>
          <td>(</td>
          <td class="paramtype">Args &amp;&amp;...&#160;</td>
          <td class="paramname"><em>args</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Add a system to the manager </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">args</td><td>the system's construction arguments </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a74e8059b19200ac24edd8fe73c2e65b5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::SystemManager::configure </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Configure all stored systems and set the initialized state to true </p>

</div>
</div>
<a class="anchor" id="aedfccb1319af97e4663dea87cdd4c3a1"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static T* NRE::ECS::SystemManager::get </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system.php" title="Base class for user defined system. ">System</a> getter </p><dl class="section return"><dt>Returns</dt><dd>the T systems </dd></dl>

</div>
</div>
<a class="anchor" id="a06ba6ff5e300b22f6e392cfb0e75319f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T* NRE::ECS::SystemManager::getSystem </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_system.php" title="Base class for user defined system. ">System</a> getter </p><dl class="section return"><dt>Returns</dt><dd>the T systems </dd></dl>

</div>
</div>
<a class="anchor" id="a01017c20cc72cd42f54207f0074c4601"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::SystemManager::update </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Update the T system </p>

</div>
</div>
<a class="anchor" id="af310e9ee3b6e45e4d03dd811392c2546"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::ECS::SystemManager::updateAll </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Update all stored systems </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/System/Manager/<a class="el" href="_n_r_e___system_manager_8hpp_source.php">NRE_SystemManager.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
