<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::ViewIterator&lt; T, All &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">ViewIterator</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::ViewIterator&lt; T, All &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>An iterator over a view of entities.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___view_iterator_8hpp_source.php">NRE_ViewIterator.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::ECS::ViewIterator&lt; T, All &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_e_c_s_1_1_view_iterator.png" usemap="#NRE::ECS::ViewIterator_3C_20T_2C_20All_20_3E_map" alt=""/>
  <map id="NRE::ECS::ViewIterator_3C_20T_2C_20All_20_3E_map" name="NRE::ECS::ViewIterator&lt; T, All &gt;_map">
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a9701e377e9c70c6d842ce09c08280c78"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9701e377e9c70c6d842ce09c08280c78">ViewIterator</a> ()=delete</td></tr>
<tr class="separator:a9701e377e9c70c6d842ce09c08280c78"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af43c19a99db764dae3629913bf5f6185"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#af43c19a99db764dae3629913bf5f6185">ViewIterator</a> (<a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> i)</td></tr>
<tr class="separator:af43c19a99db764dae3629913bf5f6185"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac2f7faf9980bb487895cfb66e5bc4ddb"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#ac2f7faf9980bb487895cfb66e5bc4ddb">ViewIterator</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> const m, <a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a> i)</td></tr>
<tr class="separator:ac2f7faf9980bb487895cfb66e5bc4ddb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9073e325fd31867c1e849521de1298bc"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a9073e325fd31867c1e849521de1298bc">~ViewIterator</a> ()=default</td></tr>
<tr class="separator:a9073e325fd31867c1e849521de1298bc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6a59facd435e716218c86772453f5a08"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a6a59facd435e716218c86772453f5a08">next</a> ()</td></tr>
<tr class="separator:a6a59facd435e716218c86772453f5a08"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a272be19d31f3f6ea28e8e8a7916ee6ff"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a272be19d31f3f6ea28e8e8a7916ee6ff">predicate</a> ()</td></tr>
<tr class="separator:a272be19d31f3f6ea28e8e8a7916ee6ff"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab21d102dfe4f120918069a9ff0f17b86"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#ab21d102dfe4f120918069a9ff0f17b86">validEntity</a> ()</td></tr>
<tr class="separator:ab21d102dfe4f120918069a9ff0f17b86"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8bb27527b0b79690886f9ac1f723bb66"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a8bb27527b0b79690886f9ac1f723bb66">operator*</a> ()</td></tr>
<tr class="separator:a8bb27527b0b79690886f9ac1f723bb66"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab30f5339d2b6d8bc054e3b551997dd3c"><td class="memItemLeft" align="right" valign="top">const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#ab30f5339d2b6d8bc054e3b551997dd3c">operator*</a> () const </td></tr>
<tr class="separator:ab30f5339d2b6d8bc054e3b551997dd3c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a602c15071a7c8e439917b1748d32c861"><td class="memItemLeft" align="right" valign="top">T &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a602c15071a7c8e439917b1748d32c861">operator++</a> ()</td></tr>
<tr class="separator:a602c15071a7c8e439917b1748d32c861"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1831ae17abb095e7d65c71f254a6a83e"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a1831ae17abb095e7d65c71f254a6a83e">operator==</a> (T const &amp;rhs) const </td></tr>
<tr class="separator:a1831ae17abb095e7d65c71f254a6a83e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2e5b536dc3b520fa335bdeac5de9a29e"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php#a2e5b536dc3b520fa335bdeac5de9a29e">operator!=</a> (T const &amp;rhs) const </td></tr>
<tr class="separator:a2e5b536dc3b520fa335bdeac5de9a29e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T, bool All = false&gt;<br />
class NRE::ECS::ViewIterator&lt; T, All &gt;</h3>

<p>An iterator over a view of entities. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a9701e377e9c70c6d842ce09c08280c78"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">ViewIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="af43c19a99db764dae3629913bf5f6185"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">ViewIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&#160;</td>
          <td class="paramname"><em>i</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a view iterator from an entity's index </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the entity's index </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ac2f7faf9980bb487895cfb66e5bc4ddb"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">ViewIterator</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> const&#160;</td>
          <td class="paramname"><em>m</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="namespace_n_r_e.php#aa87ccdbfdf4cc8a17853dbcbd09cfa18">uint32</a>&#160;</td>
          <td class="paramname"><em>i</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Construct a view iterator from an entity's index and a component mask </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">m</td><td>the entity's component mask </td></tr>
    <tr><td class="paramname">i</td><td>the entity's index </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a9073e325fd31867c1e849521de1298bc"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::~<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">ViewIterator</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php" title="An iterator over a view of entities. ">ViewIterator</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a6a59facd435e716218c86772453f5a08"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::next </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Access the next entity </p>

</div>
</div>
<a class="anchor" id="a2e5b536dc3b520fa335bdeac5de9a29e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::operator!= </td>
          <td>(</td>
          <td class="paramtype">T const &amp;&#160;</td>
          <td class="paramname"><em>rhs</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Difference test between this and rhs </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">rhs</td><td>the T type view iterator to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a8bb27527b0b79690886f9ac1f723bb66"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::operator* </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Dot dereference operator </p><dl class="section return"><dt>Returns</dt><dd>a reference on the current entity (from the current index) </dd></dl>

</div>
</div>
<a class="anchor" id="ab30f5339d2b6d8bc054e3b551997dd3c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity.php">Entity</a> <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::operator* </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Dot dereference operator </p><dl class="section return"><dt>Returns</dt><dd>a const reference on the current entity (from the current index) </dd></dl>

</div>
</div>
<a class="anchor" id="a602c15071a7c8e439917b1748d32c861"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">T&amp; <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::operator++ </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Incremental operator, pass to the next entity </p><dl class="section return"><dt>Returns</dt><dd>a reference on the iterator type </dd></dl>

</div>
</div>
<a class="anchor" id="a1831ae17abb095e7d65c71f254a6a83e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::operator== </td>
          <td>(</td>
          <td class="paramtype">T const &amp;&#160;</td>
          <td class="paramname"><em>rhs</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Equality test between this and rhs </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">rhs</td><td>the T type view iterator to test with this </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<a class="anchor" id="a272be19d31f3f6ea28e8e8a7916ee6ff"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::predicate </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The iterator predicate </p><dl class="section return"><dt>Returns</dt><dd>the predicate's result </dd></dl>

</div>
</div>
<a class="anchor" id="ab21d102dfe4f120918069a9ff0f17b86"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T, bool All = false&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_iterator.php">NRE::ECS::ViewIterator</a>&lt; T, All &gt;::validEntity </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Tell if an entity is valid </p><dl class="section return"><dt>Returns</dt><dd>the test's result </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/Iterator/<a class="el" href="_n_r_e___view_iterator_8hpp_source.php">NRE_ViewIterator.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
