<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: NRE::ECS::View&lt; All &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>ECS</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">View</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_e_c_s_1_1_view-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::ECS::View&lt; All &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Base view for advanced iterator.  
 <a href="class_n_r_e_1_1_e_c_s_1_1_view.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___view_8hpp_source.php">NRE_View.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::ECS::View&lt; All &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_e_c_s_1_1_view.png" usemap="#NRE::ECS::View_3C_20All_20_3E_map" alt=""/>
  <map id="NRE::ECS::View_3C_20All_20_3E_map" name="NRE::ECS::View&lt; All &gt;_map">
<area href="class_n_r_e_1_1_e_c_s_1_1_typed_view.php" title="A typed view. " alt="NRE::ECS::TypedView&lt; All, Components &gt;" shape="rect" coords="0,56,254,80"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A basic view iterator.  <a href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:afd2527c49829479e17b435651eabd008"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php#afd2527c49829479e17b435651eabd008">View</a> ()</td></tr>
<tr class="separator:afd2527c49829479e17b435651eabd008"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acc39cc0fb7b072e494374d8a66d22d9f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php#acc39cc0fb7b072e494374d8a66d22d9f">View</a> (<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a> m)</td></tr>
<tr class="separator:acc39cc0fb7b072e494374d8a66d22d9f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abbd9b374abea285a601d449234cacb46"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php#abbd9b374abea285a601d449234cacb46">~View</a> ()=default</td></tr>
<tr class="separator:abbd9b374abea285a601d449234cacb46"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8906736592a8a124b6bf6d781416a422"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php#a8906736592a8a124b6bf6d781416a422">begin</a> ()</td></tr>
<tr class="separator:a8906736592a8a124b6bf6d781416a422"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac523c3f54edc3d281f383c50c6f1d436"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> const&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php#ac523c3f54edc3d281f383c50c6f1d436">begin</a> () const </td></tr>
<tr class="separator:ac523c3f54edc3d281f383c50c6f1d436"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0d91d3b3bbb90886dc8dd8ebbab33281"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php#a0d91d3b3bbb90886dc8dd8ebbab33281">end</a> ()</td></tr>
<tr class="separator:a0d91d3b3bbb90886dc8dd8ebbab33281"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7b7d5f1da97bb147e03633e05b7d1d03"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> const&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php#a7b7d5f1da97bb147e03633e05b7d1d03">end</a> () const </td></tr>
<tr class="separator:a7b7d5f1da97bb147e03633e05b7d1d03"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;bool All&gt;<br />
class NRE::ECS::View&lt; All &gt;</h3>

<p>Base view for advanced iterator. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="afd2527c49829479e17b435651eabd008"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;bool All&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">NRE::ECS::View</a>&lt; All &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">View</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="acc39cc0fb7b072e494374d8a66d22d9f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;bool All&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">NRE::ECS::View</a>&lt; All &gt;::<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">View</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_entity_manager.php#af55ac31ee3c7cb0bcd8e26ccb26b5868">EntityManager::ComponentMask</a>&#160;</td>
          <td class="paramname"><em>m</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Create a view from a component mask </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">m</td><td>the view's component mask </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="abbd9b374abea285a601d449234cacb46"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;bool All&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">NRE::ECS::View</a>&lt; All &gt;::~<a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">View</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php" title="Base view for advanced iterator. ">View</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a8906736592a8a124b6bf6d781416a422"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;bool All&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">NRE::ECS::View</a>&lt; All &gt;::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Begin iterator </p><dl class="section return"><dt>Returns</dt><dd>an iterator on the begin </dd></dl>

</div>
</div>
<a class="anchor" id="ac523c3f54edc3d281f383c50c6f1d436"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;bool All&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">NRE::ECS::View</a>&lt; All &gt;::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Const Begin iterator </p><dl class="section return"><dt>Returns</dt><dd>an iterator on the begin </dd></dl>

</div>
</div>
<a class="anchor" id="a0d91d3b3bbb90886dc8dd8ebbab33281"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;bool All&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">NRE::ECS::View</a>&lt; All &gt;::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>End iterator </p><dl class="section return"><dt>Returns</dt><dd>an iterator on the end </dd></dl>

</div>
</div>
<a class="anchor" id="a7b7d5f1da97bb147e03633e05b7d1d03"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;bool All&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view_1_1_iterator.php">Iterator</a> const <a class="el" href="class_n_r_e_1_1_e_c_s_1_1_view.php">NRE::ECS::View</a>&lt; All &gt;::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Const End iterator </p><dl class="section return"><dt>Returns</dt><dd>an iterator on the end </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-ECS/src/ECS/Entity/Manager/Iterator/View/<a class="el" href="_n_r_e___view_8hpp_source.php">NRE_View.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
