<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-ECS: File List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">File List</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">Here is a list of all documented files with brief descriptions:</div><div class="directory">
<div class="levels">[detail level <span onclick="javascript:toggleLevel(1);">1</span><span onclick="javascript:toggleLevel(2);">2</span><span onclick="javascript:toggleLevel(3);">3</span><span onclick="javascript:toggleLevel(4);">4</span><span onclick="javascript:toggleLevel(5);">5</span><span onclick="javascript:toggleLevel(6);">6</span><span onclick="javascript:toggleLevel(7);">7</span><span onclick="javascript:toggleLevel(8);">8</span>]</div><table class="directory">
<tr id="row_0_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_0_" class="arrow" onclick="toggleFolder('0_')">&#9660;</span><span id="img_0_" class="iconfopen" onclick="toggleFolder('0_')">&#160;</span><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php" target="_self">src</a></td><td class="desc"></td></tr>
<tr id="row_0_0_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_0_" class="arrow" onclick="toggleFolder('0_0_')">&#9660;</span><span id="img_0_0_" class="iconfopen" onclick="toggleFolder('0_0_')">&#160;</span><a class="el" href="dir_b1a122bf62c958266ec5bf64d14fde5a.php" target="_self">ECS</a></td><td class="desc"></td></tr>
<tr id="row_0_0_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_0_0_" class="arrow" onclick="toggleFolder('0_0_0_')">&#9660;</span><span id="img_0_0_0_" class="iconfopen" onclick="toggleFolder('0_0_0_')">&#160;</span><a class="el" href="dir_9ced74f09c88343535c7b8c7200820c7.php" target="_self">Component</a></td><td class="desc"></td></tr>
<tr id="row_0_0_0_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_0_0_0_" class="arrow" onclick="toggleFolder('0_0_0_0_')">&#9660;</span><span id="img_0_0_0_0_" class="iconfopen" onclick="toggleFolder('0_0_0_0_')">&#160;</span><a class="el" href="dir_71c6ba3a8ad36a98135300822ebf3862.php" target="_self">Handle</a></td><td class="desc"></td></tr>
<tr id="row_0_0_0_0_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___component_handle_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___component_handle_8hpp.php" target="_self">NRE_ComponentHandle.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : ComponentHandle </td></tr>
<tr id="row_0_0_0_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_0_0_1_" class="arrow" onclick="toggleFolder('0_0_0_1_')">&#9660;</span><span id="img_0_0_0_1_" class="iconfopen" onclick="toggleFolder('0_0_0_1_')">&#160;</span><a class="el" href="dir_a55403350d24ea1c392642761b73cf4f.php" target="_self">Helper</a></td><td class="desc"></td></tr>
<tr id="row_0_0_0_1_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___component_helper_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___component_helper_8hpp.php" target="_self">NRE_ComponentHelper.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : ComponentHelper </td></tr>
<tr id="row_0_0_0_1_1_"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___i_component_helper_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___i_component_helper_8hpp.php" target="_self">NRE_IComponentHelper.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : IComponentHelper </td></tr>
<tr id="row_0_0_0_2_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___abstract_component_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___abstract_component_8hpp.php" target="_self">NRE_AbstractComponent.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : AbstractComponent </td></tr>
<tr id="row_0_0_0_3_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___component_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___component_8hpp.php" target="_self">NRE_Component.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : Component </td></tr>
<tr id="row_0_0_1_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_0_1_" class="arrow" onclick="toggleFolder('0_0_1_')">&#9660;</span><span id="img_0_0_1_" class="iconfopen" onclick="toggleFolder('0_0_1_')">&#160;</span><a class="el" href="dir_b3425cf3684a72a972685eae55fae74b.php" target="_self">Entity</a></td><td class="desc"></td></tr>
<tr id="row_0_0_1_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_0_1_0_" class="arrow" onclick="toggleFolder('0_0_1_0_')">&#9660;</span><span id="img_0_0_1_0_" class="iconfopen" onclick="toggleFolder('0_0_1_0_')">&#160;</span><a class="el" href="dir_195607172ac1a925227ad8dc33934fdc.php" target="_self">Id</a></td><td class="desc"></td></tr>
<tr id="row_0_0_1_0_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___id_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___id_8hpp.php" target="_self">NRE_Id.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : Id </td></tr>
<tr id="row_0_0_1_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_0_1_1_" class="arrow" onclick="toggleFolder('0_0_1_1_')">&#9660;</span><span id="img_0_0_1_1_" class="iconfopen" onclick="toggleFolder('0_0_1_1_')">&#160;</span><a class="el" href="dir_506b361a64b5c3fb8c72eb8d6abb6c67.php" target="_self">Manager</a></td><td class="desc"></td></tr>
<tr id="row_0_0_1_1_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_0_1_1_0_" class="arrow" onclick="toggleFolder('0_0_1_1_0_')">&#9660;</span><span id="img_0_0_1_1_0_" class="iconfopen" onclick="toggleFolder('0_0_1_1_0_')">&#160;</span><a class="el" href="dir_1909940746abd86c0c599cf3ad621065.php" target="_self">Allocator</a></td><td class="desc"></td></tr>
<tr id="row_0_0_1_1_0_0_"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___abstract_allocator_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___abstract_allocator_8hpp.php" target="_self">NRE_AbstractAllocator.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : AbstractAllocator </td></tr>
<tr id="row_0_0_1_1_0_1_" class="even"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___pool_allocator_8hpp_source.php"><span class="icondoc"></span></a><b>NRE_PoolAllocator.hpp</b></td><td class="desc"></td></tr>
<tr id="row_0_0_1_1_1_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span id="arr_0_0_1_1_1_" class="arrow" onclick="toggleFolder('0_0_1_1_1_')">&#9660;</span><span id="img_0_0_1_1_1_" class="iconfopen" onclick="toggleFolder('0_0_1_1_1_')">&#160;</span><a class="el" href="dir_73723887d630f5da8d29f5a815db9909.php" target="_self">Iterator</a></td><td class="desc"></td></tr>
<tr id="row_0_0_1_1_1_0_" class="even"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span id="arr_0_0_1_1_1_0_" class="arrow" onclick="toggleFolder('0_0_1_1_1_0_')">&#9660;</span><span id="img_0_0_1_1_1_0_" class="iconfopen" onclick="toggleFolder('0_0_1_1_1_0_')">&#160;</span><a class="el" href="dir_2538ef0c7acee28898444f7d785a41f8.php" target="_self">View</a></td><td class="desc"></td></tr>
<tr id="row_0_0_1_1_1_0_0_"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><span id="arr_0_0_1_1_1_0_0_" class="arrow" onclick="toggleFolder('0_0_1_1_1_0_0_')">&#9660;</span><span id="img_0_0_1_1_1_0_0_" class="iconfopen" onclick="toggleFolder('0_0_1_1_1_0_0_')">&#160;</span><a class="el" href="dir_0aff36051a98d313a3bea74a850158f9.php" target="_self">Typed</a></td><td class="desc"></td></tr>
<tr id="row_0_0_1_1_1_0_0_0_" class="even"><td class="entry"><span style="width:128px;display:inline-block;">&#160;</span><a href="_n_r_e___typed_view_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___typed_view_8hpp.php" target="_self">NRE_TypedView.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : TypedView </td></tr>
<tr id="row_0_0_1_1_1_0_1_"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><span id="arr_0_0_1_1_1_0_1_" class="arrow" onclick="toggleFolder('0_0_1_1_1_0_1_')">&#9660;</span><span id="img_0_0_1_1_1_0_1_" class="iconfopen" onclick="toggleFolder('0_0_1_1_1_0_1_')">&#160;</span><a class="el" href="dir_cec269bb69830bcdc62eb9e3e68facbb.php" target="_self">Unpacking</a></td><td class="desc"></td></tr>
<tr id="row_0_0_1_1_1_0_1_0_" class="even"><td class="entry"><span style="width:128px;display:inline-block;">&#160;</span><a href="_n_r_e___unpacking_view_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___unpacking_view_8hpp.php" target="_self">NRE_UnpackingView.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : UnpackingView </td></tr>
<tr id="row_0_0_1_1_1_0_2_"><td class="entry"><span style="width:112px;display:inline-block;">&#160;</span><a href="_n_r_e___view_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___view_8hpp.php" target="_self">NRE_View.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : View </td></tr>
<tr id="row_0_0_1_1_1_1_" class="even"><td class="entry"><span style="width:96px;display:inline-block;">&#160;</span><a href="_n_r_e___view_iterator_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___view_iterator_8hpp.php" target="_self">NRE_ViewIterator.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : ViewIterator </td></tr>
<tr id="row_0_0_1_1_2_"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___entity_manager_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___entity_manager_8hpp.php" target="_self">NRE_EntityManager.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : EntityManager </td></tr>
<tr id="row_0_0_1_2_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___entity_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___entity_8hpp.php" target="_self">NRE_Entity.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : Entity </td></tr>
<tr id="row_0_0_2_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_0_2_" class="arrow" onclick="toggleFolder('0_0_2_')">&#9660;</span><span id="img_0_0_2_" class="iconfopen" onclick="toggleFolder('0_0_2_')">&#160;</span><a class="el" href="dir_3a0ad7289f82990986345da35b146158.php" target="_self">System</a></td><td class="desc"></td></tr>
<tr id="row_0_0_2_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_0_0_2_0_" class="arrow" onclick="toggleFolder('0_0_2_0_')">&#9660;</span><span id="img_0_0_2_0_" class="iconfopen" onclick="toggleFolder('0_0_2_0_')">&#160;</span><a class="el" href="dir_d2b3eb3b820ea89e416019dba41ec760.php" target="_self">Manager</a></td><td class="desc"></td></tr>
<tr id="row_0_0_2_0_0_"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><a href="_n_r_e___system_manager_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___system_manager_8hpp.php" target="_self">NRE_SystemManager.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : SystemManager </td></tr>
<tr id="row_0_0_2_1_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___abstract_system_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___abstract_system_8hpp.php" target="_self">NRE_AbstractSystem.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : AbstractSystem </td></tr>
<tr id="row_0_0_2_2_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___system_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___system_8hpp.php" target="_self">NRE_System.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API Object : System </td></tr>
<tr id="row_0_1_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_1_" class="arrow" onclick="toggleFolder('0_1_')">&#9660;</span><span id="img_0_1_" class="iconfopen" onclick="toggleFolder('0_1_')">&#160;</span><a class="el" href="dir_0bb4bacb73d7f86c6a963ab22a4f5c20.php" target="_self">Header</a></td><td class="desc"></td></tr>
<tr id="row_0_1_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___e_c_s_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___e_c_s_8hpp.php" target="_self">NRE_ECS.hpp</a></td><td class="desc">Declaration of Engine's <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s Header </td></tr>
<tr id="row_0_2_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icondoc"></span><a class="el" href="_n_r_e___main_8cpp.php" target="_self">NRE_Main.cpp</a></td><td class="desc">Test of <a class="el" href="namespace_e_c_s.php" title="ECS&#39;s API. ">ECS</a>'s API </td></tr>
</table>
</div><!-- directory -->
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
